In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Leveranser av motorbensin, dieselbränsle, etanol och eldningsolja till slutgiltiga förbrukare, 1000 m3 efter region, varuslag och är
# region & year 
df1 = pd.read_table('../data/grouped-data/leveranser-till-slutlsiga-forbrukare-per-ar.csv', sep=',')

print(df1.columns)
print(df1.region.drop_duplicates(keep='first').reset_index(drop=True))
print(df1.varuslag.drop_duplicates(keep='first').reset_index(drop=True))


print(df1.describe)

print(df1.dtypes)

Index(['region', 'varuslag', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017'],
      dtype='object')
0                    00 Riket
1         0114 Upplands V�sby
2             0115 Vallentuna
3              0117 �ster�ker
4                 0120 V�rmd�
                ...
308         21 G�vleborgs l�n
309    22 V�sternorrlands l�n
310          23 J�mtlands l�n
311      24 V�sterbottens l�n
312        25 Norrbottens l�n
Name: region, Length: 313, dtype: object
0                                           motorbensin
1                                         dieselbr�nsle
2                                                etanol
3                                                   E85
4                                                  FAME
5                                                   HVO
6                                     eldningsolja nr 1
7              eldningsolja nr 1 d�rav ej SNI 05-33, 35
8                           eldningsolja nr 2 inkl. WRD
9     eldningsolja nr 2 inkl. WRD d�rav ej SNI 05-33...
10                                  Eldningsolja nr 2-5
11            Eldningsolja nr 2-5 d�rav ej SNI 05-33,35
12                                 eldningsolja nr 3-6
13           eldningsolja nr 3-6 d�rav ej SNI 05-33, 35
Name: varuslag, dtype: object
<bound method NDFrame.describe of                   region                                           varuslag  \
0               00 Riket                                        motorbensin
1               00 Riket                                      dieselbr�nsle
2               00 Riket                                             etanol
3               00 Riket                                                E85
4               00 Riket                                               FAME
...                  ...                                                ...
4377  25 Norrbottens l�n  eldningsolja nr 2 inkl. WRD d�rav ej SNI 05-33...
4378  25 Norrbottens l�n                                Eldningsolja nr 2-5
4379  25 Norrbottens l�n          Eldningsolja nr 2-5 d�rav ej SNI 05-33,35
4380  25 Norrbottens l�n                               eldningsolja nr 3-6
4381  25 Norrbottens l�n         eldningsolja nr 3-6 d�rav ej SNI 05-33, 35

        2001    2002    2003    2004    2005    2006    2007    2008    2009  \
0     5442.6  5494.6  5553.6  5557.4  5453.1  5306.7  5267.8  4954.8  4840.3
1     3530.0  3664.9  3856.0  4073.0  4166.6  4284.5  4468.3  4851.6  4774.1
2        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
3        0.0     0.0     0.0     0.0     0.0     0.0     0.0   209.5   208.3
4         ..      ..      ..      ..      ..      ..      ..      ..      ..
...      ...     ...     ...     ...     ...     ...     ...     ...     ...
4377      ..      ..      ..      ..      ..      ..      ..     3.1     4.4
4378    97.0   201.5   155.6   109.7   128.3   107.6    38.5      ..      ..
4379     4.8     1.4     2.9     1.8     1.9     0.0     0.0      ..      ..
4380      ..      ..      ..      ..      ..      ..      ..    90.3    39.3
4381      ..      ..      ..      ..      ..      ..      ..     3.2    11.6

        2010    2011    2012    2013    2014    2015    2016    2017
0     4568.0  4231.1  3884.2  3685.7  3540.5  3471.4  3341.3  3198.0
1     5095.7  5297.8  5277.4  5391.0  5531.6  5783.3  5859.9  5820.8
2        0.0   214.4   212.2   174.8   154.8   103.0    58.3    48.8
3      230.8     0.0     0.0     0.0      ..      ..      ..      ..
4         ..      ..      ..      ..      ..      ..    78.4    70.9
...      ...     ...     ...     ...     ...     ...     ...     ...
4377     3.8     3.2    10.3     8.8    11.1     3.1     0.0      ..
4378      ..      ..      ..      ..      ..      ..     0.0      ..
4379      ..      ..      ..      ..      ..      ..     0.0      ..
4380    37.0    89.3    17.2    75.5      ..      ..      ..      ..
4381    13.6     0.0     0.0     0.0      ..      ..      ..      ..

[4382 rows x 19 columns]>
region      object
varuslag    object
2001        object
2002        object
2003        object
2004        object
2005        object
2006        object
2007        object
2008        object
2009        object
2010        object
2011        object
2012        object
2013        object
2014        object
2015        object
2016        object
2017        object
dtype: object

In [3]:
# Elproduktion och bränsleanvändning (MWh) efter region, produktionssätt, bränsletyp och är
# fuel type & region & year
df2 = pd.read_table('../data/grouped-data/elproduktion-per-ar.csv', sep=',')

print(df2.columns)
df2.rename(columns = {'produktionss�tt':'produktionssatt', 'br�nsletyp':'bransletyp'}, inplace = True)

print(df2.region.drop_duplicates(keep='first').reset_index(drop=True))
print(df2.produktionssatt.drop_duplicates(keep='first').reset_index(drop=True))
print(df2.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))


print(df2.describe)

print(df2.dtypes)

Index(['region', 'produktionss�tt', 'br�nsletyp', '2005', '2006', '2007',
       '2008'],
      dtype='object')
0                  00 Riket
1         01 Stockholms l�n
2            03 Uppsala l�n
3      04 S�dermanlands l�n
4      05 �sterg�tlands l�n
               ...
308              2580 Lule�
309              2581 Pite�
310              2582 Boden
311          2583 Haparanda
312             2584 Kiruna
Name: region, Length: 313, dtype: object
0               kraftv�rmeverk + industriellt mottryck
1    �vrig v�rmekraft (k�rnkraft, kondenskraft o.dyl.)
2                                          vattenkraft
3                                     summa br�nsletyp
Name: produktionssatt, dtype: object
0                 elproduktion
1    flytande (icke f�rnybara)
2        fast (icke f�rnybara)
3         gas (icke f�rnybara)
4         flytande (f�rnybara)
5             fast (f�rnybara)
6              gas (f�rnybara)
7                       �vriga
8        summa produktionss�tt
Name: bransletyp, dtype: object
<bound method NDFrame.describe of             region                         produktionssatt  \
0         00 Riket  kraftv�rmeverk + industriellt mottryck
1         00 Riket  kraftv�rmeverk + industriellt mottryck
2         00 Riket  kraftv�rmeverk + industriellt mottryck
3         00 Riket  kraftv�rmeverk + industriellt mottryck
4         00 Riket  kraftv�rmeverk + industriellt mottryck
...            ...                                     ...
11263  2584 Kiruna                        summa br�nsletyp
11264  2584 Kiruna                        summa br�nsletyp
11265  2584 Kiruna                        summa br�nsletyp
11266  2584 Kiruna                        summa br�nsletyp
11267  2584 Kiruna                        summa br�nsletyp

                      bransletyp      2005      2006      2007      2008
0                   elproduktion  12064884  12760970  13531303  13831977
1      flytande (icke f�rnybara)        ..        ..   1280448        ..
2          fast (icke f�rnybara)   2310535   2996482   2323507   2733832
3           gas (icke f�rnybara)        ..    949374   1391573   1082610
4           flytande (f�rnybara)   2887038   2728526   3175003   4107044
...                          ...       ...       ...       ...       ...
11263       flytande (f�rnybara)         0         0         0         0
11264           fast (f�rnybara)     13522     13106     19688     17377
11265            gas (f�rnybara)         0         0         0         0
11266                     �vriga         0         0         0         0
11267      summa produktionss�tt     25463     24471     36829     30357

[11268 rows x 7 columns]>
region             object
produktionssatt    object
bransletyp         object
2005               object
2006               object
2007               object
2008               object
dtype: object

In [4]:
# Fjärrvärmeproduktion och bränsleanvändning (MWh) efter region, produktionssätt, bränsletyp och är
# fuel type & region & year
df3 = pd.read_table('../data/grouped-data/fjarvarmproduktion-per-ar.csv', sep=',')

print(df3.columns)
df3.rename(columns={'produktionss�tt': 'produktionssatt', 'br�nsletyp': 'bransletyp'}, inplace=True)


print(df3.region.drop_duplicates(keep='first').reset_index(drop=True))
print(df3.produktionssatt.drop_duplicates(keep='first').reset_index(drop=True))
print(df3.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))


print(df3.describe)

print(df3.dtypes)

Index(['region', 'produktionss�tt', 'br�nsletyp', '2005', '2006', '2007',
       '2008'],
      dtype='object')
0                  00 Riket
1         01 Stockholms l�n
2            03 Uppsala l�n
3      04 S�dermanlands l�n
4      05 �sterg�tlands l�n
               ...
308              2580 Lule�
309              2581 Pite�
310              2582 Boden
311          2583 Haparanda
312             2584 Kiruna
Name: region, Length: 313, dtype: object
0          kraftv�rmeverk
1    frist�ende v�rmeverk
2            elpannor (1)
3         v�rmepumpar (2)
4              spillv�rme
5           r�kgaskondens
6        summa br�nsletyp
Name: produktionssatt, dtype: object
0         fj�rrv�rmeproduktion
1    flytande (icke f�rnybara)
2        fast (icke f�rnybara)
3         gas (icke f�rnybara)
4         flytande (f�rnybara)
5             fast (f�rnybara)
6              gas (f�rnybara)
7                       �vriga
8        summa produktionss�tt
Name: bransletyp, dtype: object
<bound method NDFrame.describe of             region   produktionssatt                 bransletyp      2005  \
0         00 Riket    kraftv�rmeverk       fj�rrv�rmeproduktion  28878151
1         00 Riket    kraftv�rmeverk  flytande (icke f�rnybara)   1532682
2         00 Riket    kraftv�rmeverk      fast (icke f�rnybara)   6656244
3         00 Riket    kraftv�rmeverk       gas (icke f�rnybara)   1793869
4         00 Riket    kraftv�rmeverk       flytande (f�rnybara)    276767
...            ...               ...                        ...       ...
19714  2584 Kiruna  summa br�nsletyp       flytande (f�rnybara)         0
19715  2584 Kiruna  summa br�nsletyp           fast (f�rnybara)    115447
19716  2584 Kiruna  summa br�nsletyp            gas (f�rnybara)         0
19717  2584 Kiruna  summa br�nsletyp                     �vriga         0
19718  2584 Kiruna  summa br�nsletyp      summa produktionss�tt    213015

           2006      2007      2008
0      31540649  30934340  29740485
1       1785007    984862    614941
2       6654542   6383359   7703106
3       1661940   2043930   1646865
4        208256    273179    431200
...         ...       ...       ...
19714         0         0         0
19715    108921    127666    124679
19716         0         0         0
19717         0         0         0
19718    193167    251069    213280

[19719 rows x 7 columns]>
region             object
produktionssatt    object
bransletyp         object
2005               object
2006               object
2007               object
2008               object
dtype: object

nuclear not green and stuc for 10 years
forecasts for produciton/consuption per type and region
predictions 6 years back (try to find datasets covering periods before covid)
plan horizon for most companies 3 years
find a region to use as example (österåker/osteraker)

In [5]:
# Slutanvändning (MWh) efter region, förbrukarkategori, bränsletyp och är
# fuel type & region & year
df4 = pd.read_table('../data/grouped-data/slutanvanding-per-ar.csv', sep=',')

print(df4.columns)

df4.rename(columns={'br�nsletyp': 'bransletyp'}, inplace=True)


print(df4.region.drop_duplicates(keep='first').reset_index(drop=True))
print(df4.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))


print(df4.describe)

print(df4.dtypes)

Index(['region', 'f�rbrukarkategori', 'br�nsletyp', '2005', '2006', '2007',
       '2008'],
      dtype='object')
0                  00 Riket
1         01 Stockholms l�n
2            03 Uppsala l�n
3      04 S�dermanlands l�n
4      05 �sterg�tlands l�n
               ...
308              2580 Lule�
309              2581 Pite�
310              2582 Boden
311          2583 Haparanda
312             2584 Kiruna
Name: region, Length: 313, dtype: object
0    flytande (icke f�rnybara)
1        fast (icke f�rnybara)
2         gas (icke f�rnybara)
3         flytande (f�rnybara)
4             fast (f�rnybara)
5              gas (f�rnybara)
6                       �vriga
7                   fj�rrv�rme
8                           el
9      summa f�rbrukarkategori
Name: bransletyp, dtype: object
<bound method NDFrame.describe of             region                  f�rbrukarkategori  \
0         00 Riket  slutanv. jordbruk,skogsbruk,fiske
1         00 Riket  slutanv. jordbruk,skogsbruk,fiske
2         00 Riket  slutanv. jordbruk,skogsbruk,fiske
3         00 Riket  slutanv. jordbruk,skogsbruk,fiske
4         00 Riket  slutanv. jordbruk,skogsbruk,fiske
...            ...                                ...
28165  2584 Kiruna                   summa br�nsletyp
28166  2584 Kiruna                   summa br�nsletyp
28167  2584 Kiruna                   summa br�nsletyp
28168  2584 Kiruna                   summa br�nsletyp
28169  2584 Kiruna                   summa br�nsletyp

                      bransletyp     2005     2006     2007     2008
0      flytande (icke f�rnybara)  4195950  4158066  3689400  4003198
1          fast (icke f�rnybara)        0        0        0        0
2           gas (icke f�rnybara)        0        0        0        0
3           flytande (f�rnybara)        0        0        0        0
4               fast (f�rnybara)        0        0        0        0
...                          ...      ...      ...      ...      ...
28165            gas (f�rnybara)        0        0        0        0
28166                     �vriga        0       ..       ..       ..
28167                 fj�rrv�rme   209099   200353   198858   212578
28168                         el       ..       ..       ..  1622148
28169    summa f�rbrukarkategori       ..       ..       ..  3227532

[28170 rows x 7 columns]>
region               object
f�rbrukarkategori    object
bransletyp           object
2005                 object
2006                 object
2007                 object
2008                 object
dtype: object

In [6]:
# Elanvändning i Sverige, GWh efter användningsområde, elomröde och är
# sweden & year
df5 = pd.read_table('../data/grouped-data/elvanding-efer-anvandingsomrade-per-ar.csv', sep=',')

print(df5.columns)
df5.rename(columns={'anv�ndningsomr�de': 'anvandningsomrode', 'elomr�de': 'elomrode'}, inplace=True)

print(df5.anvandningsomrode.drop_duplicates(keep='first').reset_index(drop=True))
print(df5.elomrode.drop_duplicates(keep='first').reset_index(drop=True))

print(df5.describe)

print(df5.dtypes)

Index(['Unnamed: 0', 'anv�ndningsomr�de', 'elomr�de', '2015', '2016', '2017',
       '2018', '2019', '2020', '2021'],
      dtype='object')
0                                    summa f�rbrukad el
1                                                export
2     jord- o. skogsbruk o.d. j�mte anslutna hush�ll...
3     jord- o. skogsbruk o. d. j�mte anslutna hush�l...
4     tillverkning och utvinning av mineraler, SNI20...
5     elf�rs�rjning (kontor, lager o.d.), SNI2007 jm...
6     gasf�rs�rjning (distr. av gasformiga br�nslen ...
7      f�rs�rjning av v�rme och kyla, SNI 2007 jmf 35.3
8                                gatu- och v�gbelysning
9     vattenverk och avloppsrening, SNI2007 jmf. 36....
10    avfallshantering och renh�llning, SNI2007 jmf....
11                   byggverksamhet, SNI2007 jmf. 41-43
12    parti- och provisionshandelhandel utom med mot...
13    detaljhandel och Handel samt reparation av mot...
14    hotell- och restaurangverksamhet, SNI2007 jmf....
15    j�rnv�gstransport och kollektivtrafikverksamhe...
16    annan typ av transport. Magasinering och st�dt...
17           post- och kurirverksamhet, SNI2007 jmf. 53
18    Finans- och f�rs�kringsverksamhet, SNI2007 jmf...
19    informations- och kommunikationsverksamhet, SN...
20    reparation och installation av maskiner och ap...
21    fastighetsverksamhet; fastighetsf�rvaltning, -...
22    fastighetsverksamhet; fastighetsf�rvaltning, -...
23    uthyrning , leasing, databehandling o. a. f�re...
24    offentlig f�rvaltning och f�rsvar; obligatoris...
25    utbildning, vetenskaplig forskning och utveckl...
26    h�lso- och sjukv�rd, sociala tj�nster o.d., SN...
27      annan serviceverksamhet, SNI2007 jmf. 94-96, 99
28          kultur, n�je och fritid, SNI2007 jmf. 90-93
29    permanenta bost�der, sm�hus med f�rbrukning �v...
30    permanenta bost�der, sm�hus med f�rbrukning h�...
31    permanenta bost�der, flerbostadshus, direktlev...
32    permanenta bost�der, flerbostadshus, direktlev...
33    permanenta bost�der, flerbostadshus, kollektiv...
34                                      fritidsbost�der
35    summa slutlig f�rbrukning inom landet exkl. f�...
36                                    stamn�tsf�rluster
37                     f�rluster exkl stamn�tsf�rluster
38    summa slutlig f�rbrukning inom landet inkl. f�...
Name: anvandningsomrode, dtype: object
0    Riket
1      SE1
2      SE2
3      SE3
4      SE4
Name: elomrode, dtype: object
<bound method NDFrame.describe of      Unnamed: 0                                  anvandningsomrode elomrode  \
0             0                                 summa f�rbrukad el    Riket
1             1                                 summa f�rbrukad el      SE1
2             2                                 summa f�rbrukad el      SE2
3             3                                 summa f�rbrukad el      SE3
4             4                                 summa f�rbrukad el      SE4
..          ...                                                ...      ...
190         190  summa slutlig f�rbrukning inom landet inkl. f�...    Riket
191         191  summa slutlig f�rbrukning inom landet inkl. f�...      SE1
192         192  summa slutlig f�rbrukning inom landet inkl. f�...      SE2
193         193  summa slutlig f�rbrukning inom landet inkl. f�...      SE3
194         194  summa slutlig f�rbrukning inom landet inkl. f�...      SE4

       2015    2016    2017    2018    2019    2020    2021
0    168230  166786  172377  171862  174700  172725  176945
1        ..      ..      ..      ..      ..      ..      ..
2        ..      ..      ..      ..      ..      ..      ..
3        ..      ..      ..      ..      ..      ..      ..
4        ..      ..      ..      ..      ..      ..      ..
..      ...     ...     ...     ...     ...     ...     ...
190  136336  140764  141489  142438  139469  135901  143036
191      ..      ..      ..      ..      ..      ..      ..
192      ..      ..      ..      ..      ..      ..      ..
193      ..      ..      ..      ..      ..      ..      ..
194      ..      ..      ..      ..      ..      ..      ..

[195 rows x 10 columns]>
Unnamed: 0            int64
anvandningsomrode    object
elomrode             object
2015                 object
2016                 object
2017                 object
2018                 object
2019                 object
2020                 object
2021                 object
dtype: object

In [7]:
# Utleveranser av brånslen efter brånsleslag, tabellinnehåll och månad
# fuel type & month
df6 = pd.read_table('../data/grouped-data/utleveranser-per-ar.csv', sep=',')

print(df6.columns)
df6.columns = df6.columns.str.replace('�', 'a')

print(df6.bransleslag.drop_duplicates(keep='first').reset_index(drop=True))

print(df6.describe)

print(df6.dtypes)

Index(['br�nsleslag', 'Lagerf�r�ndringar (ton) 2018M01',
       'Lagerf�r�ndringar (ton) 2018M02', 'Lagerf�r�ndringar (ton) 2018M03',
       'Lagerf�r�ndringar (ton) 2018M04', 'Lagerf�r�ndringar (ton) 2018M05',
       'Lagerf�r�ndringar (ton) 2018M06', 'Lagerf�r�ndringar (ton) 2018M07',
       'Lagerf�r�ndringar (ton) 2018M08', 'Lagerf�r�ndringar (ton) 2018M09',
       ...
       'Utrikes bunkring (m3) 2021M12', 'Utrikes bunkring (m3) 2022M01',
       'Utrikes bunkring (m3) 2022M02', 'Utrikes bunkring (m3) 2022M03',
       'Utrikes bunkring (m3) 2022M04', 'Utrikes bunkring (m3) 2022M05',
       'Utrikes bunkring (m3) 2022M06', 'Utrikes bunkring (m3) 2022M07',
       'Utrikes bunkring (m3) 2022M08', 'Utrikes bunkring (m3) 2022M09'],
      dtype='object', length=343)
0                                          ren etanol
1                                       ren bio-nafta
2     flygbr�nsle, totalt, inkl. f�rnybar flygfotogen
3                                 ren bio-flygfotogen
4                                             ren HVO
5                                 ren annan biodiesel
6                                ren annan bio-bensin
7                                            ren FAME
8                                       EO2-6, totalt
9                                               nafta
10                                        LPG (gasol)
11                                             r�olja
12                                       halvfabrikat
13                                       ED95, totalt
14             diesel/EO1, totalt, inkl. FAME och HVO
15    motorbensin, totalt, inkl. etanol och bio-nafta
16                                        E85, totalt
Name: bransleslag, dtype: object
<bound method NDFrame.describe of                                         bransleslag  \
0                                        ren etanol
1                                     ren bio-nafta
2   flygbr�nsle, totalt, inkl. f�rnybar flygfotogen
3                               ren bio-flygfotogen
4                                           ren HVO
5                               ren annan biodiesel
6                              ren annan bio-bensin
7                                          ren FAME
8                                     EO2-6, totalt
9                                             nafta
10                                      LPG (gasol)
11                                           r�olja
12                                     halvfabrikat
13                                     ED95, totalt
14           diesel/EO1, totalt, inkl. FAME och HVO
15  motorbensin, totalt, inkl. etanol och bio-nafta
16                                      E85, totalt

   Lagerfarandringar (ton) 2018M01 Lagerfarandringar (ton) 2018M02  \
0                              873                            3491
1                             -560                            -469
2                            33358                           -2008
3                               ..                              ..
4                             7373                           22181
5                               ..                              ..
6                             1063                            -281
7                             4517                             570
8                           -76324                           55646
9                               ..                              ..
10                           13198                          -57722
11                          -57345                          -61911
12                         -118061                          -51664
13                              ..                              ..
14                           35809                         -189155
15                            -568                           -3943
16                              ..                              ..

   Lagerfarandringar (ton) 2018M03 Lagerfarandringar (ton) 2018M04  \
0                            -6703                            2758
1                            -1132                           -2062
2                           -27100                          -14564
3                               ..                              ..
4                            11427                           25983
5                               ..                              ..
6                              -60                             254
7                            -3006                            4944
8                            43733                           63625
9                               ..                              ..
10                          -87762                           -9695
11                          243246                           66756
12                              ..                           59887
13                              ..                              ..
14                         -121162                           82201
15                           -8628                           63448
16                              ..                              ..

   Lagerfarandringar (ton) 2018M05 Lagerfarandringar (ton) 2018M06  \
0                            -5677                           -2390
1                             -245                            -883
2                            37750                          -10202
3                               ..                              ..
4                           -18648                           12773
5                               ..                              ..
6                            -1033                            -177
7                              195                            1906
8                           -28618                          -74784
9                               ..                              ..
10                           24692                           37638
11                         -446149                          258715
12                           46117                          138693
13                              ..                              ..
14                           34639                         -114977
15                          -51590                          -15844
16                              ..                              ..

   Lagerfarandringar (ton) 2018M07 Lagerfarandringar (ton) 2018M08  \
0                              -37                           -3879
1                             -748                            1833
2                            19365                          -25862
3                               ..                              ..
4                             1804                          -12579
5                               ..                              ..
6                             -160                              -1
7                            -4216                           -2994
8                            29424                          -18279
9                               ..                              ..
10                           86850                           46805
11                         -244005                           14374
12                         -113046                         -136593
13                              ..                              ..
14                           55612                           34282
15                           54928                          -59397
16                            -404                              ..

   Lagerfarandringar (ton) 2018M09  ... Utrikes bunkring (m3) 2021M12  \
0                            -4799  ...                            ..
1                             -491  ...                            ..
2                            78086  ...                            ..
3                               ..  ...                            ..
4                             2903  ...                            ..
5                               ..  ...                            ..
6                              181  ...                            ..
7                            -7267  ...                            ..
8                           112943  ...                        177839
9                               ..  ...                            ..
10                            6977  ...                            ..
11                           15221  ...                            ..
12                         -183323  ...                            ..
13                              ..  ...                            ..
14                          -95840  ...                         56603
15                            9883  ...                           116
16                              ..  ...                            ..

   Utrikes bunkring (m3) 2022M01 Utrikes bunkring (m3) 2022M02  \
0                             ..                            ..
1                             ..                            ..
2                             ..                            ..
3                             ..                            ..
4                             ..                            ..
5                             ..                            ..
6                             ..                            ..
7                             ..                            ..
8                         156017                        157169
9                             ..                            ..
10                            ..                            ..
11                            ..                            ..
12                            ..                            ..
13                            ..                            ..
14                         39904                         61173
15                           102                            54
16                            ..                            ..

   Utrikes bunkring (m3) 2022M03 Utrikes bunkring (m3) 2022M04  \
0                             ..                            ..
1                             ..                            ..
2                             ..                            ..
3                             ..                            ..
4                             ..                            ..
5                             ..                            ..
6                             ..                            ..
7                             ..                            ..
8                         160357                        169498
9                             ..                            ..
10                            ..                            ..
11                            ..                            ..
12                            ..                            ..
13                            ..                            ..
14                         62158                         50171
15                           141                           246
16                            ..                            ..

   Utrikes bunkring (m3) 2022M05 Utrikes bunkring (m3) 2022M06  \
0                             ..                            ..
1                             ..                            ..
2                             ..                            ..
3                             ..                            ..
4                             ..                            ..
5                             ..                            ..
6                             ..                            ..
7                             ..                            ..
8                         209487                        107099
9                             ..                            ..
10                            ..                            ..
11                            ..                            ..
12                            ..                            ..
13                            ..                            ..
14                         47378                         48941
15                           763                          1293
16                            ..                            ..

   Utrikes bunkring (m3) 2022M07 Utrikes bunkring (m3) 2022M08  \
0                             ..                            ..
1                             ..                            ..
2                             ..                            ..
3                             ..                            ..
4                             ..                            ..
5                             ..                            ..
6                             ..                            ..
7                             ..                            ..
8                         233706                        200259
9                             ..                            ..
10                            ..                            ..
11                            ..                            ..
12                            ..                            ..
13                            ..                            ..
14                         26487                         45695
15                          2086                          1522
16                            ..                            ..

   Utrikes bunkring (m3) 2022M09
0                             ..
1                             ..
2                             ..
3                             ..
4                             ..
5                             ..
6                             ..
7                             ..
8                         192486
9                             ..
10                            ..
11                            ..
12                            ..
13                            ..
14                         56857
15                           450
16                            ..

[17 rows x 343 columns]>
bransleslag                        object
Lagerfarandringar (ton) 2018M01    object
Lagerfarandringar (ton) 2018M02    object
Lagerfarandringar (ton) 2018M03    object
Lagerfarandringar (ton) 2018M04    object
                                    ...
Utrikes bunkring (m3) 2022M05      object
Utrikes bunkring (m3) 2022M06      object
Utrikes bunkring (m3) 2022M07      object
Utrikes bunkring (m3) 2022M08      object
Utrikes bunkring (m3) 2022M09      object
Length: 343, dtype: object

In [8]:
# Utleveranser av biodrivmedel. Volym i m3 (om inte annat anges) efter varuslag och månad
# biological types & month
df7 = pd.read_table(
    '../data/grouped-data/utleveranser-av-biodrivmedel-per-ar.csv', sep=',')

print(df7.columns)

print(df7.varuslag.drop_duplicates(keep='first').reset_index(drop=True))

print(df7.describe)

print(df7.dtypes)

Index(['Unnamed: 0', 'varuslag', '2018M01', '2018M02', '2018M03', '2018M04',
       '2018M05', '2018M06', '2018M07', '2018M08', '2018M09', '2018M10',
       '2018M11', '2018M12', '2019M01', '2019M02', '2019M03', '2019M04',
       '2019M05', '2019M06', '2019M07', '2019M08', '2019M09', '2019M10',
       '2019M11', '2019M12', '2020M01', '2020M02', '2020M03', '2020M04',
       '2020M05', '2020M06', '2020M07', '2020M08', '2020M09', '2020M10',
       '2020M11', '2020M12', '2021M01', '2021M02', '2021M03', '2021M04',
       '2021M05', '2021M06', '2021M07', '2021M08', '2021M09', '2021M10',
       '2021M11', '2021M12', '2022M01', '2022M02', '2022M03', '2022M04',
       '2022M05', '2022M06', '2022M07', '2022M08', '2022M09'],
      dtype='object')
0     motorbensin, totalt, inkl. etanol och bio-nafta
1             andel l�ginblandad f�rnybar bensin  (%)
2                           varav l�ginblandad etanol
3                                          ren etanol
4                              totalt f�rnybar bensin
5                        varav l�ginblandad bio-nafta
6                                       ren bio-nafta
7                                ren annan bio-bensin
8                                         E85, totalt
9                                        etanol i E85
10                                       ED95, totalt
11                                      etanol i ED95
12                                           ren FAME
13                                            ren HVO
14                                   totalt biodiesel
15                            varav l�ginblandad FAME
16                                ren annan biodiesel
17                             varav l�ginblandad HVO
18             diesel/EO1, totalt, inkl. FAME och HVO
19                      andel l�ginblandad diesel (%)
20                                  totalt fordonsgas
21                                       varav biogas
Name: varuslag, dtype: object
<bound method NDFrame.describe of     Unnamed: 0                                         varuslag   2018M01  \
0            0  motorbensin, totalt, inkl. etanol och bio-nafta    205010
1            1          andel l�ginblandad f�rnybar bensin  (%)         5
2            2                        varav l�ginblandad etanol      9669
3            3                                       ren etanol        ..
4            4                           totalt f�rnybar bensin        ..
5            5                     varav l�ginblandad bio-nafta       707
6            6                                    ren bio-nafta        ..
7            7                             ren annan bio-bensin        ..
8            8                                      E85, totalt      2574
9            9                                     etanol i E85      1980
10          10                                     ED95, totalt        ..
11          11                                    etanol i ED95        ..
12          12                                         ren FAME      4212
13          13                                          ren HVO     46560
14          14                                 totalt biodiesel    106164
15          15                          varav l�ginblandad FAME     16629
16          16                              ren annan biodiesel        ..
17          17                           varav l�ginblandad HVO     38763
18          18           diesel/EO1, totalt, inkl. FAME och HVO    361958
19          19                    andel l�ginblandad diesel (%)        15
20          20                                totalt fordonsgas  13070687
21          21                                     varav biogas  11989161

     2018M02   2018M03   2018M04   2018M05   2018M06   2018M07   2018M08  ...  \
0     194752    225984    224050    257733    259541    281927    267116  ...
1          5         5         5         5         5         5         5  ...
2       9345     10765     10579     12039     12725     13078     12536  ...
3         ..        ..        ..        ..        ..        ..        ..  ...
4         ..        ..        ..        ..        ..        ..        ..  ...
5        322      1090       522       455       508       448       220  ...
6         ..        ..        ..        ..        ..        ..        ..  ...
7         ..        ..        ..        ..        ..        ..        ..  ...
8       2650      2709      6026      7286     10007      8310      8566  ...
9       2038      2089      4885      6089      8389      6981      7168  ...
10        ..        ..        ..        ..        ..        ..        ..  ...
11        ..        ..        ..        ..        ..        ..        ..  ...
12      4837      5530      5108      6316      6756      7599     10112  ...
13     41268     48359     43577     47379     44631     18270     19656  ...
14    105116    119818    114877    125788    127380    115169    128829  ...
15     16739     18921     20355     23928     24368     25612     27952  ...
16        ..        ..        ..        ..        ..        ..        ..  ...
17     42272     47008     45837     48165     51625     63688     71109  ...
18    376604    419551    379714    420306    430748    425681    472236  ...
19        15        15        17        17        17        21        21  ...
20  12178753  13367539  12789302  13495857  12181033  11670519  12740702  ...
21  11243973  12195572  11702011  12471485  11238982  10781130  11605294  ...

     2021M12   2022M01   2022M02   2022M03   2022M04   2022M05   2022M06  \
0     223914    186323    187369    224887    213929    240888    242658
1          9         9        10         9         9        10         9
2      19719     16761     17005     19692     19056     22686     21788
3         ..        ..        ..        ..        ..        ..        ..
4         ..        ..        ..        ..        ..        ..        ..
5         75       914      1481       599        ..       613       746
6         ..        ..        ..        ..        ..        ..        ..
7         ..        ..        ..        ..        ..        ..        ..
8        464       968      1389      1976      1831      1906      2364
9        362       745      1085      1575      1502      1557      1941
10        ..        ..        ..        ..        ..        ..        ..
11        ..        ..        ..        ..        ..        ..        ..
12      5744      5036      4599      6147      5038      5157      4769
13     21543     19397     17573     18247     16184     17597     14516
14    113103    130975    140363    142756    145045    166468    168027
15     14888     15520     19937     23781     25576     30221     28742
16        ..        ..        ..        ..        ..        ..        ..
17     70928     91022     98254     94581     98247    113493    120000
18    445364    361501    397522    449778    396082    444227    414044
19        19        29        30        26        31        32        36
20  12975675  12760977  12195417  13958109  13012977  13415163  12325630
21  12596621  12224311  11744362  13399337  12617186  12808909  11833405

     2022M07   2022M08   2022M09
0     264215    257868    225850
1          9         9        10
2      24340     24067     20627
3         ..        ..        ..
4         ..        ..        ..
5        691       115      2203
6         ..        ..        ..
7         ..        ..        ..
8       2128      2159      1378
9       1750      1778      1141
10        ..        ..        ..
11        ..        ..        ..
12      4777      5324      7065
13     13759     14130     14695
14    154583    171435    186541
15     26649     28410     29230
16        ..        ..        ..
17    109398    123571    135551
18    384712    427532    440216
19        35        36        37
20  11217855  12405990  12907146
21  10879625  11938133  12469690

[22 rows x 59 columns]>
Unnamed: 0     int64
varuslag      object
2018M01       object
2018M02       object
2018M03       object
2018M04       object
2018M05       object
2018M06       object
2018M07       object
2018M08       object
2018M09       object
2018M10       object
2018M11       object
2018M12       object
2019M01       object
2019M02       object
2019M03       object
2019M04       object
2019M05       object
2019M06       object
2019M07       object
2019M08       object
2019M09       object
2019M10       object
2019M11       object
2019M12       object
2020M01       object
2020M02       object
2020M03       object
2020M04       object
2020M05       object
2020M06       object
2020M07       object
2020M08       object
2020M09       object
2020M10       object
2020M11       object
2020M12       object
2021M01       object
2021M02       object
2021M03       object
2021M04       object
2021M05       object
2021M06       object
2021M07       object
2021M08       object
2021M09       object
2021M10       object
2021M11       object
2021M12       object
2022M01       object
2022M02       object
2022M03       object
2022M04       object
2022M05       object
2022M06       object
2022M07       object
2022M08       object
2022M09       object
dtype: object

In [9]:
# Leveranser av bränsle, kubikmeter efter region, bränsletyp, färbrukarkategori och är
# fuel type & region & year
df8 = pd.read_table(
    '../data/grouped-data/leveranser-av-bransle-per-ar.csv', sep=',')

print(df8.columns)
df8.rename(columns={'br�nsletyp': 'bransletyp', 'f�rbrukarkategori': 'forbrukarkategori'}, inplace=True)

print(df8.region.drop_duplicates(keep='first').reset_index(drop=True))
print(df8.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))
print(df8.forbrukarkategori.drop_duplicates(keep='first').reset_index(drop=True))

print(df8.describe)

print(df8.dtypes)

Index(['region', 'br�nsletyp', 'f�rbrukarkategori', '2016', '2017', '2018',
       '2019', '2020', '2021'],
      dtype='object')
0      0114 Upplands V�sby
1          0115 Vallentuna
2           0117 �ster�ker
3              0120 V�rmd�
4            0123 J�rf�lla
              ...
286             2580 Lule�
287             2581 Pite�
288             2582 Boden
289         2583 Haparanda
290            2584 Kiruna
Name: region, Length: 291, dtype: object
0                   bensin
1                   diesel
2                   etanol
3           eldningsolja 1
4           eldningsolja 2
5         eldningsolja 3-6
6                     FAME
7                      HVO
8               diesel/EO1
9            varav  diesel
10    varav eldningsolja 1
11        eldningsolja 2-6
Name: bransletyp, dtype: object
0                            jordbruk, skogsbruk, fiske
1                                              industri
2                                     el- och v�rmeverk
3                                 offentlig f�rvaltning
4                                          enbostadshus
5                                        flerbostadshus
6                                    �vriga fastigheter
7                                        v�gtransporter
8     bygg- och transporttj�nster, luftfart, j�rnv�g...
9                                                totalt
10                    bygg, luftfart, j�rnv�g, bunkring
Name: forbrukarkategori, dtype: object
<bound method NDFrame.describe of                     region bransletyp                  forbrukarkategori 2016  \
0      0114 Upplands V�sby     bensin         jordbruk, skogsbruk, fiske  0.0
1      0114 Upplands V�sby     bensin                           industri  0.0
2      0114 Upplands V�sby     bensin                  el- och v�rmeverk  0.0
3      0114 Upplands V�sby     bensin              offentlig f�rvaltning  0.0
4      0114 Upplands V�sby     bensin                       enbostadshus  0.0
...                    ...        ...                                ...  ...
46555          2584 Kiruna        HVO                     flerbostadshus  NaN
46556          2584 Kiruna        HVO                 �vriga fastigheter  NaN
46557          2584 Kiruna        HVO                     v�gtransporter  NaN
46558          2584 Kiruna        HVO  bygg, luftfart, j�rnv�g, bunkring  NaN
46559          2584 Kiruna        HVO                             totalt  NaN

      2017  2018   2019  2020   2021
0      0.0   NaN    NaN   NaN    NaN
1      0.0   NaN    NaN   NaN    NaN
2      0.0   NaN    NaN   NaN    NaN
3      0.0   NaN    NaN   NaN    NaN
4      0.0   NaN    NaN   NaN    NaN
...    ...   ...    ...   ...    ...
46555  NaN   0.0    0.0   0.0    0.0
46556  NaN   0.0    0.0   0.0     ..
46557  NaN    ..    0.0    ..  199.0
46558  NaN  71.0  121.0    ..    0.0
46559  NaN    ..  121.0  42.8  225.0

[46560 rows x 9 columns]>
region               object
bransletyp           object
forbrukarkategori    object
2016                 object
2017                 object
2018                 object
2019                 object
2020                 object
2021                 object
dtype: object

In [10]:
# bränsleanvändning efter bränsletyp, näringsgren SNI 2007 och kvartal
# fuel type & industry type and quarter
df9 = pd.read_table(
    '../data/grouped-data/bransleanvandning-after-bransletyp-per-kvartal.csv', sep=',')

print(df9.columns)
df9.rename(columns={'br�nsletyp': 'bransletyp', 'n�ringsgren SNI 2007': 'SNI2007'}, inplace=True)

print(df9.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))
print(df9.SNI2007.drop_duplicates(keep='first').reset_index(drop=True))

print(df9.describe)

print(df9.dtypes)

Index(['br�nsletyp', 'n�ringsgren SNI 2007', '2022K1', '2022k2'], dtype='object')
0                       stenkol (1000 ton)
1                          koks (1000 ton)
2              eldningsolja nr 1 (1000 m3)
3            eldningsolja nr 2-6 (1000 m3)
4                         gasol (1000 ton)
5                  tr�dbr�nslen (1000 toe)
6    avlutar, tall och beckolja (1000 toe)
7                          torv (1000 toe)
8                        avfall (1000 toe)
Name: bransletyp, dtype: object
0     05-33 tillverkningsindustri; gruvor och minera...
1            05-09 gruvor och mineralutvinningsindustri
2     10-12 livsmedels-, dryckesvaru- och tobaksindu...
3     13-15 textil-, bekl�dnads-, l�der - och l�derv...
4     16 industri f�r tr� och varor av tr�, kork och...
5           17 massa-, pappers- och pappersvaruindustri
6                                   17.11 massaindustri
7                       17.12 pappers- och pappindustri
8            18 grafisk och annan reproduktionsindustri
9     19-21 kemisk industri, petroleumprodukter och ...
10                      22 gummi- och plastvaruindustri
11    23 industri f�r andra icke-metalliska minerali...
12                              24 st�l- och metallverk
13                          24.1-24.3 j�rn och st�lverk
14    25 industri f�r metallvaror utom maskiner och ...
15                        29-30 transportmedelsindustri
16    26-28 industri f�r datorer, elektronikvaror, o...
17    31-33 �vrig tillverkningsindustri, reparations...
Name: SNI2007, dtype: object
<bound method NDFrame.describe of              bransletyp                                            SNI2007  \
0    stenkol (1000 ton)  05-33 tillverkningsindustri; gruvor och minera...
1    stenkol (1000 ton)         05-09 gruvor och mineralutvinningsindustri
2    stenkol (1000 ton)  10-12 livsmedels-, dryckesvaru- och tobaksindu...
3    stenkol (1000 ton)  13-15 textil-, bekl�dnads-, l�der - och l�derv...
4    stenkol (1000 ton)  16 industri f�r tr� och varor av tr�, kork och...
..                  ...                                                ...
157   avfall (1000 toe)                        24.1-24.3 j�rn och st�lverk
158   avfall (1000 toe)  25 industri f�r metallvaror utom maskiner och ...
159   avfall (1000 toe)                      29-30 transportmedelsindustri
160   avfall (1000 toe)  26-28 industri f�r datorer, elektronikvaror, o...
161   avfall (1000 toe)  31-33 �vrig tillverkningsindustri, reparations...

    2022K1 2022k2
0      183    144
1       40     28
2       ..     ..
3       ..     ..
4       ..     ..
..     ...    ...
157     ..     ..
158     ..     ..
159     ..     ..
160     ..     ..
161     ..     ..

[162 rows x 4 columns]>
bransletyp    object
SNI2007       object
2022K1        object
2022k2        object
dtype: object

In [11]:
# Elproduktion efter produktionsslag och månad
# type of production & month
df10 = pd.read_table(
    '../data/grouped-data/elproduktion-per-manad.csv', sep=',')

print(df10.columns)


print(df10.produktionsslag.drop_duplicates(keep='first').reset_index(drop=True))

print(df10.describe)

print(df10.dtypes)

Index(['Unnamed: 0', 'produktionsslag', '2017M01', '2017M02', '2017M03',
       '2017M04', '2017M05', '2017M06', '2017M07', '2017M08', '2017M09',
       '2017M10', '2017M11', '2017M12', '2018M01', '2018M02', '2018M03',
       '2018M04', '2018M05', '2018M06', '2018M07', '2018M08', '2018M09',
       '2018M10', '2018M11', '2018M12', '2019M01', '2019M02', '2019M03',
       '2019M04', '2019M05', '2019M06', '2019M07', '2019M08', '2019M09',
       '2019M10', '2019M11', '2019M12', '2020M01', '2020M02', '2020M03',
       '2020M04', '2020M05', '2020M06', '2020M07', '2020M08', '2020M09',
       '2020M10', '2020M11', '2020M12', '2021M01', '2021M02', '2021M03',
       '2021M04', '2021M05', '2021M06', '2021M07', '2021M08', '2021M09',
       '2021M10', '2021M11', '2021M12', '2022M01', '2022M02', '2022M03',
       '2022M04', '2022M05', '2022M06', '2022M07', '2022M08', '2022M09'],
      dtype='object')
0     total elproduktion netto
1    kraftv�rme icke-f�rnybart
2         kraftv�rme f�rnybart
3                    vindkraft
4                  vattenkraft
5                    k�rnkraft
6                     solkraft
Name: produktionsslag, dtype: object
<bound method NDFrame.describe of    Unnamed: 0            produktionsslag 2017M01 2017M02 2017M03 2017M04  \
0           0   total elproduktion netto   16220   14575   15293   13722
1           1  kraftv�rme icke-f�rnybart     397     380     330     232
2           2       kraftv�rme f�rnybart    1343    1252    1274    1136
3           3                  vindkraft    1983    1370    1716    1453
4           4                vattenkraft    5807    5457    5419    4753
5           5                  k�rnkraft    6690    6116    6555    6150
6           6                   solkraft      ..      ..      ..      ..

  2017M05 2017M06 2017M07 2017M08  ... 2021M12 2022M01 2022M02 2022M03  \
0   12428   10727   11286   10954  ...   17084   17022   15377   16124
1     168     157     185     125  ...     345     210     145     189
2     869     698     643     671  ...    1649    1571    1347    1467
3    1090    1315    1022    1134  ...    2996    4225    3636    3319
4    4626    4102    5144    5369  ...    7089    6039    5857    5845
5    5674    4455    4291    3656  ...    4996    4947    4336    5108
6      ..      ..      ..      ..  ...       9      30      56     196

  2022M04 2022M05 2022M06 2022M07 2022M08 2022M09
0   13931   13010   11996   13066   13071   12192
1     171     167     159     150     153     136
2    1255     988     760     715     752     837
3    2236    2768    1856    2250    1939    2008
4    5572    5072    5282    5576    5686    5633
5    4475    3754    3666    4088    4256    3378
6     222     261     273     287     285     200

[7 rows x 71 columns]>
Unnamed: 0          int64
produktionsslag    object
2017M01            object
2017M02            object
2017M03            object
                    ...
2022M05             int64
2022M06             int64
2022M07             int64
2022M08             int64
2022M09             int64
Length: 71, dtype: object

In [12]:
# bränslefärbrukning fär elproduktion, TJ efter produktionsslag, bränsletyp och är
# type of production & fuel type & year
df11 = pd.read_table(
    '../data/grouped-data/branslefarbrukning-per-ar.csv', sep=',')

print(df11.columns)

df11.rename(columns={'br�nsletyp': 'bransletyp'}, inplace=True)

print(df11.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))

print(df11.describe)

print(df11.dtypes)

Index(['produktionsslag', 'br�nsletyp', '1990', '1991', '1992', '1993', '1994',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')
0                                 eldningsolja nr 1
1                                 eldningsolja nr 2
2                           eldningsolja nr 2 och 3
3                               eldningsolja nr 3-5
4                                 eldningsolja nr 4
5                     eldningsolja nr 5 och d�r�ver
6                                           stenkol
7                            torv och torvbriketter
8                            f�r�dlade tr�dbr�nslen
9     tr�dbr�nslen exklusive f�r�dlade tr�dbr�nslen
10                                          fotogen
11                                    dieselbr�nsle
12                                         naturgas
13                                           biogas
14                                      koksugnsgas
15                          masugnsgas inkl. LD-gas
16                   svartlutar, tall- och beckolja
17                                 propan och butan
18                                      k�rnbr�nsle
19                                           avfall
20                                    annat br�nsle
21                      summa br�nsle och drivmedel
22                   �verskotts�nga fr�n industrin
23                summa br�nsle, drivmedel och �nga
24      v�rmekraftproduktion brutto inkl. k�rnkraft
Name: bransletyp, dtype: object
<bound method NDFrame.describe of                           produktionsslag  \
0    kraftv�rme-industri, kraftv�rmedrift
1    kraftv�rme-industri, kraftv�rmedrift
2    kraftv�rme-industri, kraftv�rmedrift
3    kraftv�rme-industri, kraftv�rmedrift
4    kraftv�rme-industri, kraftv�rmedrift
..                                    ...
195                                 summa
196                                 summa
197                                 summa
198                                 summa
199                                 summa

                                      bransletyp    1990    1991    1992  \
0                              eldningsolja nr 1       0       2       0
1                              eldningsolja nr 2       0       0       0
2                        eldningsolja nr 2 och 3       0       0       0
3                            eldningsolja nr 3-5       0       0       0
4                              eldningsolja nr 4     243     265     198
..                                           ...     ...     ...     ...
195                                annat br�nsle     897    1647    2083
196                  summa br�nsle och drivmedel  754334  855710  718193
197               �verskotts�nga fr�n industrin      674     796     806
198            summa br�nsle, drivmedel och �nga  755008  856506  718999
199  v�rmekraftproduktion brutto inkl. k�rnkraft      ..      ..      ..

       1993    1994    1995    1996    1997  ...    2012    2013    2014  \
0         0     405       0       0     107  ...       4       2       6
1         0       0       0       0       0  ...       7       7      13
2         0       0       0       0       0  ...       0       0       0
3         0       0       0   11934    7631  ...    1234     894     706
4       288     240     231       0       0  ...       0       0       0
..      ...     ...     ...     ...     ...  ...     ...     ...     ...
195    2285    2564    1930     519     508  ...    3402    2680    3185
196  699871  835048  794777  894501  792272  ...  722901  734061  713916
197    1147    1067    1185     851     544  ...       0       0       0
198  701018  836114  795962  895351  792816  ...  722901  734061  713916
199      ..      ..      ..      ..      ..  ...      ..      ..      ..

       2015    2016    2017    2018    2019    2020    2021
0        26      22      12      47      39      50      46
1        47      21      15      11      10       7      33
2         0       0       0       0       0       0      ..
3       446     558     556     584     496     390     442
4         0       0       0       0       0       0      ..
..      ...     ...     ...     ...     ...     ...     ...
195    2947    3187    4267    4537    5181    3517    6114
196  624742  709958  717226  757187  762703  566571  621598
197       0       0       0       0       0       0      ..
198  624742  709958  717226  757187  762703  566571  621598
199      ..      ..      ..      ..      ..      ..      ..

[200 rows x 34 columns]>
produktionsslag    object
bransletyp         object
1990               object
1991               object
1992               object
1993               object
1994               object
1995               object
1996               object
1997               object
1998               object
1999               object
2000               object
2001               object
2002               object
2003               object
2004               object
2005               object
2006               object
2007               object
2008               object
2009               object
2010               object
2011               object
2012               object
2013               object
2014               object
2015               object
2016               object
2017               object
2018               object
2019               object
2020               object
2021               object
dtype: object

In [13]:
# Bruttoäverfäring av el till och från andra lånder, GWh efter land och månad
# year import/export & month
df12 = pd.read_table(
    '../data/grouped-data/bruttoaverfaring-per-manad.csv', sep=',')

print(df12.columns)

print(df12.land.drop_duplicates(keep='first').reset_index(drop=True))

print(df12.describe)

print(df12.dtypes)

Index(['land', '2019M01', '2019M02', '2019M03', '2019M04', '2019M05',
       '2019M06', '2019M07', '2019M08', '2019M09', '2019M10', '2019M11',
       '2019M12', '2020M01', '2020M02', '2020M03', '2020M04', '2020M05',
       '2020M06', '2020M07', '2020M08', '2020M09', '2020M10', '2020M11',
       '2020M12', '2021M01', '2021M02', '2021M03', '2021M04', '2021M05',
       '2021M06', '2021M07', '2021M08', '2021M09', '2021M10', '2021M11',
       '2021M12', '2022M01', '2022M02', '2022M03', '2022M04', '2022M05',
       '2022M06', '2022M07', '2022M08', '2022M09'],
      dtype='object')
0        Total Export
1        Total Import
2      Export Finland
3      Export Litauen
4        Export Norge
5        Export Polen
6     Export Tyskland
7      Export Danmark
8      Import Danmark
9      Import Finland
10     Import Litauen
11       Import Norge
12       Import Polen
13    Import Tyskland
Name: land, dtype: object
<bound method NDFrame.describe of                land  2019M01  2019M02  2019M03  2019M04  2019M05  2019M06  \
0      Total Export     2484     2685     3123     2800     2632     3913
1      Total Import     1378      767      749      548      296      194
2    Export Finland     1417     1085     1080      980     1052     1179
3    Export Litauen      222      195      183      278      269      456
4      Export Norge      438      720     1216      747      528      646
5      Export Polen      216      244      275      287      270      310
6   Export Tyskland       81      103       90      110      116      237
7    Export Danmark      109      338      280      398      397     1084
8    Import Danmark      485      278      465      200       54       15
9    Import Finland        0        7       19       11        9        2
10   Import Litauen       54       59       61       18        4        0
11     Import Norge      708      321      121      251      206      164
12     Import Polen       79       49       30        2        0        0
13  Import Tyskland       53       54       55       67       21       13

    2019M07  2019M08  2019M09  ...  2021M12  2022M01  2022M02  2022M03  \
0      3598     2620     2420  ...     3022     3350     2867     3306
1       669     1247      960  ...     1039      635      363      323
2      1695     1533     1586  ...     1357     1412     1246      922
3       410      438      289  ...      357      461      386      362
4       116       70       24  ...      182      279      261      254
5       313        9      225  ...      305      345      219      377
6       223       86       98  ...      220      297      246      383
7       841      483      197  ...      601      556      509     1008
8        76      169      211  ...      268      116      114       25
9         0        0        0  ...        0        0        0        0
10        0        3        0  ...       17        3        3        5
11      574      984      706  ...      675      498      227      286
12        0        0        0  ...       56       11        5        3
13       18       91       42  ...       23        7       14        4

    2022M04  2022M05  2022M06  2022M07  2022M08  2022M09
0      2795     3230     3363     4404     3928     2714
1       355      422      683      359      391      160
2       797     1096     1501     1763     1516     1030
3       293      348      412      501      486      432
4       490      275       67      187      174      410
5       319      351      321      428      429      147
6       237      268      204      334      324      276
7       659      892      858     1191      999      419
8       113       56       11        7        0       56
9         9        5        1        2        3        5
10        6        3        0        0        0        0
11      206      336      667      349      388       93
12        8       12        2        1        0        0
13       13       10        2        0        0        6

[14 rows x 46 columns]>
land       object
2019M01     int64
2019M02     int64
2019M03     int64
2019M04     int64
2019M05     int64
2019M06     int64
2019M07     int64
2019M08     int64
2019M09     int64
2019M10     int64
2019M11     int64
2019M12     int64
2020M01     int64
2020M02     int64
2020M03     int64
2020M04     int64
2020M05     int64
2020M06     int64
2020M07     int64
2020M08     int64
2020M09     int64
2020M10     int64
2020M11     int64
2020M12     int64
2021M01     int64
2021M02     int64
2021M03     int64
2021M04     int64
2021M05     int64
2021M06     int64
2021M07     int64
2021M08     int64
2021M09     int64
2021M10     int64
2021M11     int64
2021M12     int64
2022M01     int64
2022M02     int64
2022M03     int64
2022M04     int64
2022M05     int64
2022M06     int64
2022M07     int64
2022M08     int64
2022M09     int64
dtype: object

In [14]:
# bränsleanvändning efter bränsletyp, produktion, anlåggning och kvartal
# fuel type & quarter
df13 = pd.read_table(
    '../data/grouped-data/bransleanvandning-per-kvartal.csv', sep=',')

print(df13.columns)

df13.rename(columns={'br�nsletyp': 'bransletyp', 'anl�ggning': 'anlaggning'}, inplace=True)

print(df13.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))
print(df13.produktion.drop_duplicates(keep='first').reset_index(drop=True))
print(df13.anlaggning.drop_duplicates(keep='first').reset_index(drop=True))


print(df13.describe)

print(df13.dtypes)

Index(['br�nsletyp', 'produktion', 'anl�ggning', '2022K1', '2022k2'], dtype='object')
0                         eldningsolja nr 1 (1000 m3)
1                       eldningsolja nr 2-6 (1000 m3)
2                                   bioolja (1000 m3)
3                                  stenkol (1000 ton)
4                                    gasol (1000 ton)
5                   tr� (flis, bark, sp�n) (1000 toe)
6                            tr�bricketter (1000 toe)
7                     avlutar och tallolja (1000 toe)
8                                   avfall (1000 toe)
9                                     torv (1000 toe)
10                          koksugnsgas (miljoner m3)
11                           masugnsgas (miljoner m3)
12                             k�rnbr�nsle (1000 toe)
13                             naturgas (miljoner m3)
14              flytande naturgas (LNG) (miljoner m3)
15                         �vriga br�nslen (1000 toe)
16                                     elpannor (GWh)
17                                   solf�ngare (GWh)
18                                  v�rmepumpar (GWh)
19           tillf�rd v�rme fr�n andra sektorer (GWh)
20                                   spillv�rme (GWh)
21    anv�ndning av el f�r drift av v�rmepumpar (GWh)
Name: bransletyp, dtype: object
0           total produktion
1           produktion av el
2    produktion av hetvatten
Name: produktion, dtype: object
0                 samtliga anl�ggningar
1                        v�rmekraftverk
2    industriella mottrycksanl�ggningar
3                        kraftv�rmeverk
4                  frist�ende v�rmeverk
Name: anlaggning, dtype: object
<bound method NDFrame.describe of                                           bransletyp               produktion  \
0                        eldningsolja nr 1 (1000 m3)         total produktion
1                        eldningsolja nr 1 (1000 m3)         total produktion
2                        eldningsolja nr 1 (1000 m3)         total produktion
3                        eldningsolja nr 1 (1000 m3)         total produktion
4                        eldningsolja nr 1 (1000 m3)         total produktion
..                                               ...                      ...
325  anv�ndning av el f�r drift av v�rmepumpar (GWh)  produktion av hetvatten
326  anv�ndning av el f�r drift av v�rmepumpar (GWh)  produktion av hetvatten
327  anv�ndning av el f�r drift av v�rmepumpar (GWh)  produktion av hetvatten
328  anv�ndning av el f�r drift av v�rmepumpar (GWh)  produktion av hetvatten
329  anv�ndning av el f�r drift av v�rmepumpar (GWh)  produktion av hetvatten

                             anlaggning 2022K1 2022k2
0                 samtliga anl�ggningar     ..     ..
1                        v�rmekraftverk     ..     ..
2    industriella mottrycksanl�ggningar     ..     ..
3                        kraftv�rmeverk     ..     ..
4                  frist�ende v�rmeverk     ..     ..
..                                  ...    ...    ...
325               samtliga anl�ggningar     ..     ..
326                      v�rmekraftverk     ..     ..
327  industriella mottrycksanl�ggningar     ..     ..
328                      kraftv�rmeverk    131     36
329                frist�ende v�rmeverk     84     27

[330 rows x 5 columns]>
bransletyp    object
produktion    object
anlaggning    object
2022K1        object
2022k2        object
dtype: object

In [15]:
# Uttagspunkter efter användningsområde, elomröde och är
# industry type & year
df14 = pd.read_table('../data/grouped-data/uttagspunkter-per-ar.csv', sep=',')

print(df14.columns)

df14.rename(columns={'anv�ndningsomr�de': 'anvandningsomrode', 'elomr�de': 'elomrode'}, inplace=True)

print(df14.anvandningsomrode.drop_duplicates(keep='first').reset_index(drop=True))
print(df14.elomrode.drop_duplicates(keep='first').reset_index(drop=True))

print(df14.describe)

print(df14.dtypes)

Index(['anv�ndningsomr�de', 'elomr�de', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021'],
      dtype='object')
0                                                 summa
1     jord- o. skogsbruk o.d. j�mte anslutna hush�ll...
2     jord- o. skogsbruk o. d. j�mte anslutna hush�l...
3     tillverkning och utvinning av mineraler, SNI20...
4     elf�rs�rjning (kontor, lager o.d.), SNI2007 jm...
5     gasf�rs�rjning (distr. av gasformiga br�nslen ...
6      f�rs�rjning av v�rme och kyla, SNI 2007 jmf 35.3
7                                gatu- och v�gbelysning
8     vattenverk och avloppsrening, SNI2007 jmf. 36....
9     avfallshantering och renh�llning, SNI2007 jmf....
10                   byggverksamhet, SNI2007 jmf. 41-43
11    parti- och provisionshandelhandel utom med mot...
12    detaljhandel och Handel samt reparation av mot...
13    hotell- och restaurangverksamhet, SNI2007 jmf....
14    j�rnv�gstransport och kollektivtrafikverksamhe...
15    annan typ av transport. Magasinering och st�dt...
16           post- och kurirverksamhet, SNI2007 jmf. 53
17    Finans- och f�rs�kringsverksamhet, SNI2007 jmf...
18    informations- och kommunikationsverksamhet, SN...
19    reparation och installation av maskiner och ap...
20    fastighetsverksamhet; fastighetsf�rvaltning, -...
21    fastighetsverksamhet; fastighetsf�rvaltning, -...
22    uthyrning , leasing, databehandling o. a. f�re...
23    offentlig f�rvaltning och f�rsvar; obligatoris...
24    utbildning, vetenskaplig forskning och utveckl...
25    h�lso- och sjukv�rd, sociala tj�nster o.d., SN...
26      annan serviceverksamhet, SNI2007 jmf. 94-96, 99
27          kultur, n�je och fritid, SNI2007 jmf. 90-93
28    permanenta bost�der, sm�hus med f�rbrukning �v...
29    permanenta bost�der, sm�hus med f�rbrukning h�...
30    permanenta bost�der, flerbostadshus, direktlev...
31    permanenta bost�der, flerbostadshus, direktlev...
32    permanenta bost�der, flerbostadshus, kollektiv...
33                                      fritidsbost�der
Name: anvandningsomrode, dtype: object
0    Riket
1      SE1
2      SE2
3      SE3
4      SE4
Name: elomrode, dtype: object
<bound method NDFrame.describe of     anvandningsomrode elomrode     2015     2016     2017     2018     2019  \
0               summa    Riket  5417424  5431540  5466575  5512741  5555101
1               summa      SE1   184918   188026   186808   189304   191831
2               summa      SE2   459636   456944   458731   460409   463947
3               summa      SE3  3650641  3659007  3687089  3721094  3749705
4               summa      SE4  1122229  1127563  1133947  1141934  1149618
..                ...      ...      ...      ...      ...      ...      ...
165   fritidsbost�der    Riket   511536   506907   450817   445663   446961
166   fritidsbost�der      SE1    29008    28282    28655    27883    28007
167   fritidsbost�der      SE2    81827    82104    74228    74384    74719
168   fritidsbost�der      SE3   302781   298762   249823   244786   246409
169   fritidsbost�der      SE4    97920    97759    98111    98610    97826

        2020     2021
0    5581211  5605611
1     193182   203955
2     463942   457388
3    3764018  3781269
4    1160069  1162999
..       ...      ...
165   443202   442393
166    28137    31167
167    75387    73641
168   242813   241942
169    96865    95643

[170 rows x 9 columns]>
anvandningsomrode    object
elomrode             object
2015                  int64
2016                  int64
2017                  int64
2018                  int64
2019                  int64
2020                  int64
2021                  int64
dtype: object

In [16]:
# Fjärrkyla efter tabellinnehåll och är
# cooling type & year
df15 = pd.read_table('../data/grouped-data/fjarrkyla-per-ar.csv', sep=',')

print(df15.columns)

print(df15.describe)

print(df15.dtypes)

Index(['Unnamed: 0', 'Installerad effekt, MW 2018',
       'Installerad effekt, MW 2019', 'Installerad effekt, MW 2020',
       'Installerad effekt, MW 2021', 'Producerad kyla, GWh 2018',
       'Producerad kyla, GWh 2019', 'Producerad kyla, GWh 2020',
       'Producerad kyla, GWh 2021', 'Levererad kyla, GWh 2018',
       'Levererad kyla, GWh 2019', 'Levererad kyla, GWh 2020',
       'Levererad kyla, GWh 2021'],
      dtype='object')
<bound method NDFrame.describe of    Unnamed: 0  Installerad effekt, MW 2018  Installerad effekt, MW 2019  \
0         NaN                          818                          870

   Installerad effekt, MW 2020  Installerad effekt, MW 2021  \
0                          927                          947

   Producerad kyla, GWh 2018  Producerad kyla, GWh 2019  \
0                       1177                       1065

   Producerad kyla, GWh 2020  Producerad kyla, GWh 2021  \
0                       1053                       1094

   Levererad kyla, GWh 2018  Levererad kyla, GWh 2019  \
0                      1242                      1098

   Levererad kyla, GWh 2020  Levererad kyla, GWh 2021
0                      1048                      1052  >
Unnamed: 0                     float64
Installerad effekt, MW 2018      int64
Installerad effekt, MW 2019      int64
Installerad effekt, MW 2020      int64
Installerad effekt, MW 2021      int64
Producerad kyla, GWh 2018        int64
Producerad kyla, GWh 2019        int64
Producerad kyla, GWh 2020        int64
Producerad kyla, GWh 2021        int64
Levererad kyla, GWh 2018         int64
Levererad kyla, GWh 2019         int64
Levererad kyla, GWh 2020         int64
Levererad kyla, GWh 2021         int64
dtype: object

In [17]:
# not
# anlåggningar, installerad effekt samt bruttoproduktion efter elomröde, kraftslag, tabellinnehåll och är
# e & year
df16 = pd.read_table('../data/grouped-data/anlaggningar-per-ar.csv', sep=',')

print(df16.columns)

df16.rename(columns={'elomr�de': 'elomrode'}, inplace=True)

print(df16.elomrode.drop_duplicates(keep='first').reset_index(drop=True))

# print(df16.describe)

# print(df16.dtypes)

Index(['elomr�de', 'kraftslag', 'Antal anl�ggningar 2015',
       'Antal anl�ggningar 2016', 'Antal anl�ggningar 2017',
       'Antal anl�ggningar 2018', 'Antal anl�ggningar 2019',
       'Antal anl�ggningar 2020', 'Antal anl�ggningar 2021',
       'Installerad generatoreffekt, MW 2015',
       'Installerad generatoreffekt, MW 2016',
       'Installerad generatoreffekt, MW 2017',
       'Installerad generatoreffekt, MW 2018',
       'Installerad generatoreffekt, MW 2019',
       'Installerad generatoreffekt, MW 2020',
       'Installerad generatoreffekt, MW 2021', 'Bruttoproduktion, GWh 2015',
       'Bruttoproduktion, GWh 2016', 'Bruttoproduktion, GWh 2017',
       'Bruttoproduktion, GWh 2018', 'Bruttoproduktion, GWh 2019',
       'Bruttoproduktion, GWh 2020', 'Bruttoproduktion, GWh 2021'],
      dtype='object')
0    Riket
1      SE1
2      SE2
3      SE3
4      SE4
Name: elomrode, dtype: object

In [18]:
# Omsatt värme efter kategori, tabellinnehåll och är
# heating type & year
df17 = pd.read_table('../data/grouped-data/omsatt-per-ar.csv', sep=',')

print(df17.columns)

print(df17.kategori.drop_duplicates(keep='first').reset_index(drop=True))


print(df17.describe)

print(df17.dtypes)

Index(['kategori', 'Kraftv�rmeproduktion, GWh 2015',
       'Kraftv�rmeproduktion, GWh 2016', 'Kraftv�rmeproduktion, GWh 2017',
       'Kraftv�rmeproduktion, GWh 2018', 'Kraftv�rmeproduktion, GWh 2019',
       'Kraftv�rmeproduktion, GWh 2020', 'Kraftv�rmeproduktion, GWh 2021',
       'Enbart v�rmeproduktion, GWh 2015', 'Enbart v�rmeproduktion, GWh 2016',
       'Enbart v�rmeproduktion, GWh 2017', 'Enbart v�rmeproduktion, GWh 2018',
       'Enbart v�rmeproduktion, GWh 2019', 'Enbart v�rmeproduktion, GWh 2020',
       'Enbart v�rmeproduktion, GWh 2021', 'R�kgaskondensering, GWh 2015',
       'R�kgaskondensering, GWh 2016', 'R�kgaskondensering, GWh 2017',
       'R�kgaskondensering, GWh 2018', 'R�kgaskondensering, GWh 2019',
       'R�kgaskondensering, GWh 2020', 'R�kgaskondensering, GWh 2021',
       'Med elpanna producerad fj�rrv�rme, GWh 2015',
       'Med elpanna producerad fj�rrv�rme, GWh 2016',
       'Med elpanna producerad fj�rrv�rme, GWh 2017',
       'Med elpanna producerad fj�rrv�rme, GWh 2018',
       'Med elpanna producerad fj�rrv�rme, GWh 2019',
       'Med elpanna producerad fj�rrv�rme, GWh 2020',
       'Med elpanna producerad fj�rrv�rme, GWh 2021',
       'Med v�rmepump producerad fj�rrv�rme, GWh 2015',
       'Med v�rmepump producerad fj�rrv�rme, GWh 2016',
       'Med v�rmepump producerad fj�rrv�rme, GWh 2017',
       'Med v�rmepump producerad fj�rrv�rme, GWh 2018',
       'Med v�rmepump producerad fj�rrv�rme, GWh 2019',
       'Med v�rmepump producerad fj�rrv�rme, GWh 2020',
       'Med v�rmepump producerad fj�rrv�rme, GWh 2021',
       'Mottagen v�rme utom branschen, GWh 2015',
       'Mottagen v�rme utom branschen, GWh 2016',
       'Mottagen v�rme utom branschen, GWh 2017',
       'Mottagen v�rme utom branschen, GWh 2018',
       'Mottagen v�rme utom branschen, GWh 2019',
       'Mottagen v�rme utom branschen, GWh 2020',
       'Mottagen v�rme utom branschen, GWh 2021',
       'Mottagen v�rme inom branschen, GWh 2015',
       'Mottagen v�rme inom branschen, GWh 2016',
       'Mottagen v�rme inom branschen, GWh 2017',
       'Mottagen v�rme inom branschen, GWh 2018',
       'Mottagen v�rme inom branschen, GWh 2019',
       'Mottagen v�rme inom branschen, GWh 2020',
       'Mottagen v�rme inom branschen, GWh 2021',
       'F�rluster fram till leveranspunkt, GWh 2015',
       'F�rluster fram till leveranspunkt, GWh 2016',
       'F�rluster fram till leveranspunkt, GWh 2017',
       'F�rluster fram till leveranspunkt, GWh 2018',
       'F�rluster fram till leveranspunkt, GWh 2019',
       'F�rluster fram till leveranspunkt, GWh 2020',
       'F�rluster fram till leveranspunkt, GWh 2021',
       'F�rbrukning av el vid v�rmeverksdrift exkl elpannor och v�rmepumpar, GWh 2015',
       'F�rbrukning av el vid v�rmeverksdrift exkl elpannor och v�rmepumpar, GWh 2016',
       'F�rbrukning av el vid v�rmeverksdrift exkl elpannor och v�rmepumpar, GWh 2017',
       'F�rbrukning av el vid v�rmeverksdrift exkl elpannor och v�rmepumpar, GWh 2018',
       'F�rbrukning av el vid v�rmeverksdrift exkl elpannor och v�rmepumpar, GWh 2019',
       'F�rbrukning av el vid v�rmeverksdrift exkl elpannor och v�rmepumpar, GWh 2020',
       'F�rbrukning av el vid v�rmeverksdrift exkl elpannor och v�rmepumpar, GWh 2021',
       'F�rbrukning av el f�r elpannedrift, GWh 2015',
       'F�rbrukning av el f�r elpannedrift, GWh 2016',
       'F�rbrukning av el f�r elpannedrift, GWh 2017',
       'F�rbrukning av el f�r elpannedrift, GWh 2018',
       'F�rbrukning av el f�r elpannedrift, GWh 2019',
       'F�rbrukning av el f�r elpannedrift, GWh 2020',
       'F�rbrukning av el f�r elpannedrift, GWh 2021',
       'F�rbrukning av el f�r v�rmepumpsdrift, GWh 2015',
       'F�rbrukning av el f�r v�rmepumpsdrift, GWh 2016',
       'F�rbrukning av el f�r v�rmepumpsdrift, GWh 2017',
       'F�rbrukning av el f�r v�rmepumpsdrift, GWh 2018',
       'F�rbrukning av el f�r v�rmepumpsdrift, GWh 2019',
       'F�rbrukning av el f�r v�rmepumpsdrift, GWh 2020',
       'F�rbrukning av el f�r v�rmepumpsdrift, GWh 2021',
       'Br�nslef�rbrukning f�r kraftv�rmeproduktion, GWh 2015',
       'Br�nslef�rbrukning f�r kraftv�rmeproduktion, GWh 2016',
       'Br�nslef�rbrukning f�r kraftv�rmeproduktion, GWh 2017',
       'Br�nslef�rbrukning f�r kraftv�rmeproduktion, GWh 2018',
       'Br�nslef�rbrukning f�r kraftv�rmeproduktion, GWh 2019',
       'Br�nslef�rbrukning f�r kraftv�rmeproduktion, GWh 2020',
       'Br�nslef�rbrukning f�r kraftv�rmeproduktion, GWh 2021',
       'Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2015',
       'Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2016',
       'Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2017',
       'Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2018',
       'Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2019',
       'Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2020',
       'Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2021',
       'Verkningsgrad netto, procent 2015',
       'Verkningsgrad netto, procent 2016',
       'Verkningsgrad netto, procent 2017',
       'Verkningsgrad netto, procent 2018',
       'Verkningsgrad netto, procent 2019',
       'Verkningsgrad netto, procent 2020',
       'Verkningsgrad netto, procent 2021'],
      dtype='object')
0    konventionell v�rmekraft, fj�rrv�rme
1                    frist�ende v�rmeverk
2                                   summa
Name: kategori, dtype: object
<bound method NDFrame.describe of                                kategori Kraftv�rmeproduktion, GWh 2015  \
0  konventionell v�rmekraft, fj�rrv�rme                          23408
1                  frist�ende v�rmeverk                             ..
2                                 summa                          23408

  Kraftv�rmeproduktion, GWh 2016 Kraftv�rmeproduktion, GWh 2017  \
0                          25570                          25930
1                             ..                             ..
2                          25570                          25930

  Kraftv�rmeproduktion, GWh 2018 Kraftv�rmeproduktion, GWh 2019  \
0                          25427                          26497
1                             ..                             ..
2                          25427                          26497

  Kraftv�rmeproduktion, GWh 2020 Kraftv�rmeproduktion, GWh 2021  \
0                          22269                          26471
1                             ..                             ..
2                          22269                          26471

   Enbart v�rmeproduktion, GWh 2015  Enbart v�rmeproduktion, GWh 2016  ...  \
0                              7437                              7588  ...
1                             10537                             11016  ...
2                             17974                             18604  ...

   Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2019  \
0                                               6541
1                                              11911
2                                              18452

   Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2020  \
0                                               7901
1                                              11070
2                                              18972

   Br�nslef�rbrukning f�r enbart v�rmeproduktion, GWh 2021  \
0                                               7467
1                                              14349
2                                              21817

   Verkningsgrad netto, procent 2015  Verkningsgrad netto, procent 2016  \
0                               82.2                               82.8
1                               85.8                               83.5
2                               83.1                               83.0

   Verkningsgrad netto, procent 2017  Verkningsgrad netto, procent 2018  \
0                               81.6                               82.2
1                               82.6                               81.1
2                               81.8                               82.4

   Verkningsgrad netto, procent 2019  Verkningsgrad netto, procent 2020  \
0                               81.5                               80.9
1                               82.8                               81.5
2                               81.1                               81.0

   Verkningsgrad netto, procent 2021
0                               82.2
1                               82.8
2                               82.4

[3 rows x 99 columns]>
kategori                              object
Kraftv�rmeproduktion, GWh 2015        object
Kraftv�rmeproduktion, GWh 2016        object
Kraftv�rmeproduktion, GWh 2017        object
Kraftv�rmeproduktion, GWh 2018        object
                                      ...
Verkningsgrad netto, procent 2017    float64
Verkningsgrad netto, procent 2018    float64
Verkningsgrad netto, procent 2019    float64
Verkningsgrad netto, procent 2020    float64
Verkningsgrad netto, procent 2021    float64
Length: 99, dtype: object

In [19]:
# Nettoproduktion av el, bränsleanvändning samt verkningsgrad efter kraftslag, tabellinnehåll och är
# & year
df18 = pd.read_table(
    '../data/grouped-data/nettoproduktion-per-ar.csv', sep=',')

print(df18.columns)

print(df18.kraftslag.drop_duplicates(keep='first').reset_index(drop=True))

print(df18.describe)

print(df18.dtypes)

Index(['kraftslag', 'Nettoproduktion, GWh 2015', 'Nettoproduktion, GWh 2016',
       'Nettoproduktion, GWh 2017', 'Nettoproduktion, GWh 2018',
       'Nettoproduktion, GWh 2019', 'Nettoproduktion, GWh 2020',
       'Nettoproduktion, GWh 2021', 'Br�nsleinsats, GWh 2015',
       'Br�nsleinsats, GWh 2016', 'Br�nsleinsats, GWh 2017',
       'Br�nsleinsats, GWh 2018', 'Br�nsleinsats, GWh 2019',
       'Br�nsleinsats, GWh 2020', 'Br�nsleinsats, GWh 2021',
       'Verkningsgrad netto, procent 2015',
       'Verkningsgrad netto, procent 2016',
       'Verkningsgrad netto, procent 2017',
       'Verkningsgrad netto, procent 2018',
       'Verkningsgrad netto, procent 2019',
       'Verkningsgrad netto, procent 2020',
       'Verkningsgrad netto, procent 2021'],
      dtype='object')
0                k�rnkraft
1     kraftv�rmeproduktion
2    industriellt mottryck
3            kondenskraft
4              gasturbiner
5                   annan
Name: kraftslag, dtype: object
<bound method NDFrame.describe of                kraftslag  Nettoproduktion, GWh 2015  \
0              k�rnkraft                      54347
1   kraftv�rmeproduktion                       7784
2  industriellt mottryck                       5613
3          kondenskraft                          11
4            gasturbiner                          9
5                 annan                           1

   Nettoproduktion, GWh 2016  Nettoproduktion, GWh 2017  \
0                      60542                      63008
1                       9072                       9007
2                       5527                       5986
3                          9                          3
4                          7                          7
5                          6                          1

   Nettoproduktion, GWh 2018  Nettoproduktion, GWh 2019  \
0                      65801                      64334
1                       9091                       9091
2                       5914                       6716
3                          4                          3
4                         13                          8
5                          1                          1

   Nettoproduktion, GWh 2020  Nettoproduktion, GWh 2021  \
0                      47262                      50992
1                       6739                       8790
2                       6378                       6653
3                         12                        106
4                         10                         17
5                          3                          7

   Br�nsleinsats, GWh 2015  Br�nsleinsats, GWh 2016  ...  \
0                   155401                   177777  ...
1                     9919                    11397  ...
2                     8138                     7955  ...
3                       41                       33  ...
4                       37                       32  ...
5                        3                       16  ...

   Br�nsleinsats, GWh 2019  Br�nsleinsats, GWh 2020  Br�nsleinsats, GWh 2021  \
0                   189441                   138124                   150287
1                    11444                     8726                    11369
2                    10950                    10448                    10616
3                       14                       40                      304
4                       33                       41                       63
5                        1                        2                       27

   Verkningsgrad netto, procent 2015  Verkningsgrad netto, procent 2016  \
0                               35.0                               34.1
1                               78.5                               79.6
2                               69.0                               69.5
3                               28.2                               27.1
4                               25.4                               21.0
5                               37.6                               38.7

   Verkningsgrad netto, procent 2017  Verkningsgrad netto, procent 2018  \
0                               35.3                               34.7
1                               78.5                               78.9
2                               66.6                               65.9
3                               19.3                               21.1
4                               19.6                               22.1
5                               38.6                               35.7

   Verkningsgrad netto, procent 2019  Verkningsgrad netto, procent 2020  \
0                               34.0                               34.2
1                               79.4                               77.2
2                               61.3                               61.0
3                               24.2                               30.1
4                               25.1                               24.2
5                               39.3                               33.6

   Verkningsgrad netto, procent 2021
0                               33.9
1                               77.3
2                               62.7
3                               34.9
4                               26.4
5                               24.8

[6 rows x 22 columns]>
kraftslag                             object
Nettoproduktion, GWh 2015              int64
Nettoproduktion, GWh 2016              int64
Nettoproduktion, GWh 2017              int64
Nettoproduktion, GWh 2018              int64
Nettoproduktion, GWh 2019              int64
Nettoproduktion, GWh 2020              int64
Nettoproduktion, GWh 2021              int64
Br�nsleinsats, GWh 2015                int64
Br�nsleinsats, GWh 2016                int64
Br�nsleinsats, GWh 2017                int64
Br�nsleinsats, GWh 2018                int64
Br�nsleinsats, GWh 2019                int64
Br�nsleinsats, GWh 2020                int64
Br�nsleinsats, GWh 2021                int64
Verkningsgrad netto, procent 2015    float64
Verkningsgrad netto, procent 2016    float64
Verkningsgrad netto, procent 2017    float64
Verkningsgrad netto, procent 2018    float64
Verkningsgrad netto, procent 2019    float64
Verkningsgrad netto, procent 2020    float64
Verkningsgrad netto, procent 2021    float64
dtype: object

In [23]:
# Värmeleveranser till slutliga färbrukare efter färbrukarkategori, tabellinnehåll och är
# heating type & year 
df19 = pd.read_table(
    '../data/grouped-data/varmeleveranser-per-ar.csv', sep=',')

print(df19.columns)

# print('region\n', df19.region.drop_duplicates(keep='first').reset_index(drop=True))
# print('varuslag\n', df19.varuslag.drop_duplicates(keep='first').reset_index(drop=True))

print(df19.describe)

print(df19.dtypes)

Index(['anv�ndningsomr�de', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994',
       ...
       'Egenanv�ndning 2012', 'Egenanv�ndning 2013', 'Egenanv�ndning 2014',
       'Egenanv�ndning 2015', 'Egenanv�ndning 2016', 'Egenanv�ndning 2017',
       'Egenanv�ndning 2018', 'Egenanv�ndning 2019', 'Egenanv�ndning 2020',
       'Egenanv�ndning 2021'],
      dtype='object', length=145)
<bound method NDFrame.describe of                                      anv�ndningsomr�de    1986    1987  \
0                                   summa f�rbrukad el  135520  143695
1                                               export    6494    6344
2    jord- o. skogsbruk o. fiske j�mte anslutna hus...    1295    1333
3    jord- o. skogsbruk o. fiske j�mte anslutna hus...      ..      ..
4    jord- o. skogsbruk o. fiske j�mte anslutna hus...    2097    2157
..                                                 ...     ...     ...
217                                    fritidsbost�der     NaN     NaN
218  summa slutlig f�rbrukning inom landet exkl. f�...     NaN     NaN
219                                  stamn�tsf�rluster     NaN     NaN
220                   f�rluster exkl stamn�tsf�rluster     NaN     NaN
221  summa slutlig f�rbrukning inom landet inkl. f�...     NaN     NaN

       1988    1989    1990      1991      1992 1993 1994  ...  \
0    146174  150902  154622  148656.0  150626.0  NaN  NaN  ...
1      7671   12526   14677    7519.0   11003.0  NaN  NaN  ...
2      1310    1335    1536     715.0     682.0  NaN  NaN  ...
3        ..      ..      ..     958.0     895.0  NaN  NaN  ...
4      1949    1888    1664    1628.0    1449.0  NaN  NaN  ...
..      ...     ...     ...       ...       ...  ...  ...  ...
217     NaN     NaN     NaN       NaN       NaN  NaN  NaN  ...
218     NaN     NaN     NaN       NaN       NaN  NaN  NaN  ...
219     NaN     NaN     NaN       NaN       NaN  NaN  NaN  ...
220     NaN     NaN     NaN       NaN       NaN  NaN  NaN  ...
221     NaN     NaN     NaN       NaN       NaN  NaN  NaN  ...

    Egenanv�ndning 2012 Egenanv�ndning 2013 Egenanv�ndning 2014  \
0                   NaN                 NaN                 NaN
1                   NaN                 NaN                 NaN
2                   NaN                 NaN                 NaN
3                   NaN                 NaN                 NaN
4                   NaN                 NaN                 NaN
..                  ...                 ...                 ...
217                 NaN                 NaN                 NaN
218                 NaN                 NaN                 NaN
219                 NaN                 NaN                 NaN
220                 NaN                 NaN                 NaN
221                 NaN                 NaN                 NaN

    Egenanv�ndning 2015 Egenanv�ndning 2016 Egenanv�ndning 2017  \
0                   NaN                 NaN                 NaN
1                   NaN                 NaN                 NaN
2                   NaN                 NaN                 NaN
3                   NaN                 NaN                 NaN
4                   NaN                 NaN                 NaN
..                  ...                 ...                 ...
217                 NaN                 NaN                 NaN
218                 NaN                 NaN                 NaN
219                 NaN                 NaN                 NaN
220                 NaN                 NaN                 NaN
221                 NaN                 NaN                 NaN

    Egenanv�ndning 2018 Egenanv�ndning 2019 Egenanv�ndning 2020  \
0                   NaN                 NaN                 NaN
1                   NaN                 NaN                 NaN
2                   NaN                 NaN                 NaN
3                   NaN                 NaN                 NaN
4                   NaN                 NaN                 NaN
..                  ...                 ...                 ...
217                 NaN                 NaN                 NaN
218                 NaN                 NaN                 NaN
219                 NaN                 NaN                 NaN
220                 NaN                 NaN                 NaN
221                 NaN                 NaN                 NaN

    Egenanv�ndning 2021
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
..                  ...
217                 NaN
218                 NaN
219                 NaN
220                 NaN
221                 NaN

[222 rows x 145 columns]>
anv�ndningsomr�de       object
1986                    object
1987                    object
1988                    object
1989                    object
                        ...
Egenanv�ndning 2017    float64
Egenanv�ndning 2018    float64
Egenanv�ndning 2019    float64
Egenanv�ndning 2020    float64
Egenanv�ndning 2021    float64
Length: 145, dtype: object

In [24]:
# Tillfärsel av el-energi, GWh efter produktionsslag, tabellinnehåll och är
# & year
df20 = pd.read_table('../data/grouped-data/tillfarsel-per-ar.csv', sep=',')

print(df20.columns)

print('produktionsslag\n', df20.produktionsslag.drop_duplicates(keep='first').reset_index(drop=True))

print(df20.describe)

print(df20.dtypes)

Index(['Unnamed: 0', 'produktionsslag', 'Brutto 1986', 'Brutto 1987',
       'Brutto 1988', 'Brutto 1989', 'Brutto 1990', 'Brutto 1991',
       'Brutto 1992', 'Brutto 1993',
       ...
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020'],
      dtype='object', length=146)
produktionsslag
 0                                total tillf�rsel av el
1                                           vattenkraft
2                                             pumpkraft
3                                             k�rnkraft
4                  konventionell v�rmekraft, fj�rrv�rme
5                    konventionell v�rmekraft, industri
6                                             vindkraft
7                                              solkraft
8           konventionell v�rmekraft, kondensproduktion
9     konventionell v�rmekraft, gasturbin- och annan...
10                                               import
11                                                  NaN
Name: produktionsslag, dtype: object
<bound method NDFrame.describe of      Unnamed: 0                       produktionsslag Brutto 1986 Brutto 1987  \
0             0                total tillf�rsel av el      140486      148745
1             1                           vattenkraft       60933       71854
2             2                             pumpkraft         567         594
3             3                             k�rnkraft       69951       67385
4             4  konventionell v�rmekraft, fj�rrv�rme        3550        3311
..          ...                                   ...         ...         ...
175          37                                   NaN         NaN         NaN
176          38                                   NaN         NaN         NaN
177          39                                   NaN         NaN         NaN
178          40                                   NaN         NaN         NaN
179          41                                   NaN         NaN         NaN

    Brutto 1988 Brutto 1989 Brutto 1990 Brutto 1991 Brutto 1992 Brutto 1993  \
0        151294      155144      159417      153609      155292      153791
1         69883       71750       72509       63249       74364       74647
2           589         175         530         426         529         565
3         69424       65603       68185       76761       63544       61395
4          2861        2310        2290        3540        4136        4929
..          ...         ...         ...         ...         ...         ...
175         NaN         NaN         NaN         NaN         NaN         NaN
176         NaN         NaN         NaN         NaN         NaN         NaN
177         NaN         NaN         NaN         NaN         NaN         NaN
178         NaN         NaN         NaN         NaN         NaN         NaN
179         NaN         NaN         NaN         NaN         NaN         NaN

     ...      2011      2012      2013      2014      2015      2016  \
0    ...       NaN       NaN       NaN       NaN       NaN       NaN
1    ...       NaN       NaN       NaN       NaN       NaN       NaN
2    ...       NaN       NaN       NaN       NaN       NaN       NaN
3    ...       NaN       NaN       NaN       NaN       NaN       NaN
4    ...       NaN       NaN       NaN       NaN       NaN       NaN
..   ...       ...       ...       ...       ...       ...       ...
175  ...    2749.0    3043.0    2964.0    2851.0    3047.0    3212.0
176  ...  130579.0  131904.0  129192.0  125041.0  126797.0  130095.0
177  ...    2522.0    3476.0    2824.0    3087.0    3234.0    3076.0
178  ...    7194.0    7490.0    7179.0    6205.0    6305.0    7593.0
179  ...  140295.0  142870.0  139195.0  134333.0  136336.0  140764.0

         2017      2018      2019      2020
0         NaN       NaN       NaN       NaN
1         NaN       NaN       NaN       NaN
2         NaN       NaN       NaN       NaN
3         NaN       NaN       NaN       NaN
4         NaN       NaN       NaN       NaN
..        ...       ...       ...       ...
175    3040.0    2979.0    2931.0    2831.0
176  130460.0  130572.0  127372.0  125210.0
177    3423.0    3200.0    3275.0    3909.0
178    7606.0    8666.0    8822.0    6782.0
179  141489.0  142438.0  139469.0  135901.0

[180 rows x 146 columns]>
Unnamed: 0           int64
produktionsslag     object
Brutto 1986         object
Brutto 1987         object
Brutto 1988         object
                    ...
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
Length: 146, dtype: object

In [25]:
# bränslefärbrukning fär produktion av ånga och hetvatten, TJ efter produktionsslag, bränsletyp och är
# fuel type & year
df21 = pd.read_table(
    '../data/grouped-data/branslefarbrukning-far-produktion-per-ar.csv', sep=',')

print(df21.columns)

df21.rename(columns={'br�nsletyp': 'bransletyp'}, inplace=True)

print('bransletyp\n', df21.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))

print(df21.describe)

print(df21.dtypes)

Index(['produktionsslag', 'br�nsletyp', '1990', '1991', '1992', '1993', '1994',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')
bransletyp
 0                                 eldningsolja nr 1
1                                 eldningsolja nr 2
2                           eldningsolja nr 2 och 3
3                               eldningsolja nr 3-5
4                                 eldningsolja nr 4
5                     eldningsolja nr 5 och d�r�ver
6                                           stenkol
7                            torv och torvbriketter
8                            f�r�dlade tr�dbr�nslen
9     tr�dbr�nslen exklusive f�r�dlade tr�dbr�nslen
10                                          fotogen
11                                    dieselbr�nsle
12                                         naturgas
13                                           biogas
14                         stadsgas och koksugnsgas
15                          masugnsgas inkl. LD-gas
16                   svartlutar, tall- och beckolja
17                                 propan och butan
18                                           avfall
19                                    annat br�nsle
20                      summa br�nsle och drivmedel
Name: bransletyp, dtype: object
<bound method NDFrame.describe of                           produktionsslag                      bransletyp  \
0   kraftv�rme-v�rmeverk, kraftv�rmedrift               eldningsolja nr 1
1   kraftv�rme-v�rmeverk, kraftv�rmedrift               eldningsolja nr 2
2   kraftv�rme-v�rmeverk, kraftv�rmedrift         eldningsolja nr 2 och 3
3   kraftv�rme-v�rmeverk, kraftv�rmedrift             eldningsolja nr 3-5
4   kraftv�rme-v�rmeverk, kraftv�rmedrift               eldningsolja nr 4
..                                    ...                             ...
79                                  summa  svartlutar, tall- och beckolja
80                                  summa                propan och butan
81                                  summa                          avfall
82                                  summa                   annat br�nsle
83                                  summa     summa br�nsle och drivmedel

     1990    1991    1992    1993    1994    1995    1996    1997  ...  \
0      39     184     581     562    1605    1213    2982     586  ...
1       0       0       0       0       0       0       3       0  ...
2       4       8     201    1006     704     440       0       0  ...
3       0       0       0       0       0       0    8678    4521  ...
4     166     162     211     208     237     118       0       0  ...
..    ...     ...     ...     ...     ...     ...     ...     ...  ...
79      0       0       0    1651    4288    5229    6151    4988  ...
80   1815    2175    2917    2409    3099    3701    4636    2176  ...
81  14119   14203   14748   15080   14545   16022   15888   17258  ...
82    609    2275    1501    2139    2064    2089    2654    2077  ...
83  88400  101553  102521  112602  125461  127984  155824  134487  ...

      2012    2013    2014    2015    2016    2017    2018    2019    2020  \
0      540     262     333     549     862     446     662     736     354
1       51      30      27      83      85      80     106      10      26
2        0       0       0       0       0       0       0       0       0
3     1906    1102     606     267     690     397     532     305      38
4        0       0       0       0       0       0       0       0       0
..     ...     ...     ...     ...     ...     ...     ...     ...     ...
79    2848    2058    1855     766    2775    2774    2688    2119    2305
80     307     159      76      50     107      61      68      42      23
81   43076   45787   48710   51650   53898   56346   52642   56176   64313
82   15175   12492   13742   11667   12376   13874   16525   16035   15141
83  183162  183822  170782  172415  184175  180682  182696  179470  163927

      2021
0      586
1       17
2       ..
3      261
4       ..
..     ...
79    1085
80      71
81   61478
82   24763
83  191188

[84 rows x 34 columns]>
produktionsslag    object
bransletyp         object
1990                int64
1991                int64
1992                int64
1993                int64
1994                int64
1995                int64
1996                int64
1997                int64
1998                int64
1999                int64
2000                int64
2001                int64
2002                int64
2003                int64
2004                int64
2005                int64
2006                int64
2007                int64
2008                int64
2009                int64
2010                int64
2011                int64
2012                int64
2013                int64
2014               object
2015               object
2016                int64
2017                int64
2018                int64
2019                int64
2020                int64
2021               object
dtype: object

In [26]:
# bränsleanvändning, 1000 toe efter näringsgren SNI92, bränsletyp och kvartal
# industry type & fuel type & year
df22 = pd.read_table(
    '../data/grouped-data/branslefarbrukning-after-naringsgren-per-kvartal.csv', sep=',')

print(df22.columns)

df22.rename(columns={'n�ringsgren SNI92': 'SNI92', 'br�nsletyp': 'bransletyp'}, inplace=True)


print('SNI92\n', df22.SNI92.drop_duplicates(keep='first').reset_index(drop=True))
print('bransletyp\n', df22.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))


print(df22.describe)

print(df22.dtypes)

Index(['n�ringsgren SNI92', 'br�nsletyp', '1992K1', '1992K2', '1992K3',
       '1992K4', '1993K1', '1993K2', '1993K3', '1993K4', '1994K1', '1994K2',
       '1994K3', '1994K4', '1995K1', '1995K2', '1995K3', '1995K4', '1996K1',
       '1996K2', '1996K3', '1996K4', '1997K1', '1997K2', '1997K3', '1997K4',
       '1998K1', '1998K2', '1998K3', '1998K4', '1999K1', '1999K2', '1999K3',
       '1999K4', '2000K1', '2000K2', '2000K3', '2000K4', '2001K1', '2001K2',
       '2001K3', '2001K4'],
      dtype='object')
SNI92
 0       C+D utvinning av mineral, tillverkningsindustri
1                     C gruvor och mineralutvinningsind
2          15+16 livsmedels-, dryckesvaru-, o tobaksind
3     17-19 textil-, bekl�dnads-, l�der- o l�dervaruind
4     20 ind f tr� o varor av tr�, kork, rotting, ej...
5     21+22 massa- o pappersindustri; F�rlag och gra...
6     23.1+23.3+24 stenkolsprod, k�rnbr�nsle; kemisk...
7                       25 gummi- och plastvaruindustri
8                         26 jord- och stenvaruindustri
9                               27 st�l- och metallverk
10    27.1-27.3 j�rn- och st�lverk; prim�rbearbetnin...
11    28 industri f�r metallvaror utom maskiner och ...
12      29 maskinindustri som ej ing�r i annan underavd
13            30-33 industri f�r el- och optikprodukter
14                        34+35 transportmedelsindustri
15                    36+37 �vrig tillverkningsindustri
16                           40 el-, gas- och v�rmeverk
Name: SNI92, dtype: object
bransletyp
 0                                    eldningsolja nr 1
1                                  eldningsolja nr 2-6
2                                              stenkol
3                                                 koks
4                            propan, butan, l�ttbensin
5    tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...
6                                             naturgas
Name: bransletyp, dtype: object
<bound method NDFrame.describe of                                                SNI92  \
0    C+D utvinning av mineral, tillverkningsindustri
1    C+D utvinning av mineral, tillverkningsindustri
2    C+D utvinning av mineral, tillverkningsindustri
3    C+D utvinning av mineral, tillverkningsindustri
4    C+D utvinning av mineral, tillverkningsindustri
..                                               ...
114                       40 el-, gas- och v�rmeverk
115                       40 el-, gas- och v�rmeverk
116                       40 el-, gas- och v�rmeverk
117                       40 el-, gas- och v�rmeverk
118                       40 el-, gas- och v�rmeverk

                                            bransletyp 1992K1 1992K2 1992K3  \
0                                    eldningsolja nr 1     79     50     35
1                                  eldningsolja nr 2-6    199    135    123
2                                              stenkol    129    101     94
3                                                 koks    246    224    170
4                            propan, butan, l�ttbensin    113    100     83
..                                                 ...    ...    ...    ...
114                                            stenkol    293     85     25
115                                               koks     ..     ..     ..
116                          propan, butan, l�ttbensin     48     23     12
117  tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...    452    260    167
118                                           naturgas    165     43     15

    1992K4 1993K1 1993K2 1993K3 1993K4  ... 1999K3 1999K4 2000K1 2000K2  \
0       67     77     49     44     76  ...     49     78     90     47
1      216    240    171    146    282  ...    170    270    340    200
2      127    111    110    101    135  ...     88    128    144    126
3      252    214    253    185    269  ...    198    272    280    290
4      117     96     84     77    102  ...     76    107    121     94
..     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...
114    302    326     83     36    239  ...      7    134    190     43
115     ..     ..     ..     ..     ..  ...     ..     ..     ..     ..
116     52     51     16     13     43  ...     10     27     27     10
117    463    508    268    186    572  ...    258    829    953    460
118    131    165     31     24    139  ...      9    113    152     28

    2000K3 2000K4 2001K1 2001K2 2001K3 2001K4
0       38     59     87     57     45     72
1      172    220    290    198    165    238
2      100    149    144    139    131    147
3      197    268    272    239    208    267
4       77     88     99     96     71     97
..     ...    ...    ...    ...    ...    ...
114     10     77    171     41      0     99
115     ..     ..     ..     ..      0     ..
116     12     16     28      3     12     23
117    290    771   1076    541    274    906
118     20     68    158     44     14    105

[119 rows x 42 columns]>
SNI92         object
bransletyp    object
1992K1        object
1992K2        object
1992K3        object
1992K4        object
1993K1        object
1993K2        object
1993K3        object
1993K4        object
1994K1        object
1994K2        object
1994K3        object
1994K4        object
1995K1        object
1995K2        object
1995K3        object
1995K4        object
1996K1        object
1996K2        object
1996K3        object
1996K4        object
1997K1        object
1997K2        object
1997K3        object
1997K4        object
1998K1        object
1998K2        object
1998K3        object
1998K4        object
1999K1        object
1999K2        object
1999K3        object
1999K4        object
2000K1        object
2000K2        object
2000K3        object
2000K4        object
2001K1        object
2001K2        object
2001K3        object
2001K4        object
dtype: object

In [27]:
# bränsleanvändning, terajoule (TJ) efter näringsgren SNI 2007, bränsletyp och kvartal
# industry type & fuel type & year
df23 = pd.read_table(
    '../data/grouped-data/branslefarbrukning-SNI2007-per-kvartal.csv', sep=',')

print(df23.columns)

df23.rename(columns={'n�ringsgren SNI 2007': 'SNI2007', 'br�nsletyp': 'bransletyp'}, inplace=True)

print('SNI2007\n', df23.SNI2007.drop_duplicates(keep='first').reset_index(drop=True))
print('bransletyp\n', df23.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))


print(df23.describe)

print(df23.dtypes)

Index(['n�ringsgren SNI 2007', 'br�nsletyp', '2009K1', '2009K2', '2009K3',
       '2009K4', '2010K1', '2010K2', '2010K3', '2010K4', '2011K1', '2011K2',
       '2011K3', '2011K4', '2012K1', '2012K2', '2012K3', '2012K4', '2013K1',
       '2013K2', '2013K3', '2013K4', '2014K1', '2014K2', '2014K3', '2014K4',
       '2015K1', '2015K2', '2015K3', '2015K4', '2016K1', '2016K2', '2016K3',
       '2016K4', '2017K1', '2017K2', '2017K3', '2017K4', '2018K1', '2018K2',
       '2018K3', '2018K4', '2019K1', '2019K2', '2019K3', '2019K4', '2020K1',
       '2020K2', '2020K3', '2020K4', '2021K1', '2021K2', '2021K3', '2021K4',
       '2022K1', '2022k2'],
      dtype='object')
SNI2007
 0     B+C tillverkningsindustri; gruvor och mineralu...
1                B gruvor och mineralutvinningsindustri
2              10+12 livsmedelsindustri; tobaksindustri
3     13-15 textil-, bekl�dnads-, l�der - och l�derv...
4     16 industri f�r tr� och varor av tr�, kork och...
5     17-18 massa-, pappers- och pappersvaruindustri...
6     19.1+21+24.46 industri f�r stenkolsprodukter; ...
7                       22 gummi- och plastvaruindustri
8     23 industri f�r andra icke-metalliska minerali...
9                               24 st�l- och metallverk
10                          24.1-24.3 j�rn och st�lverk
11    25 industri f�r metallvaror utom maskiner och ...
12    26-28 industri f�r datorer, elektronikvaror, o...
13                        29-30 transportmedelsindustri
14    31+33 m�belindustri; reparationsverkst�der och...
15                           35 el-, gas- och v�rmeverk
Name: SNI2007, dtype: object
bransletyp
 0                                    eldningsolja nr 1
1                                  eldningsolja nr 2-6
2                                              stenkol
3                                                 koks
4    tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...
5                                             naturgas
6                                     propan och butan
Name: bransletyp, dtype: object
<bound method NDFrame.describe of                                                SNI2007  \
0    B+C tillverkningsindustri; gruvor och mineralu...
1    B+C tillverkningsindustri; gruvor och mineralu...
2    B+C tillverkningsindustri; gruvor och mineralu...
3    B+C tillverkningsindustri; gruvor och mineralu...
4    B+C tillverkningsindustri; gruvor och mineralu...
..                                                 ...
107                         35 el-, gas- och v�rmeverk
108                         35 el-, gas- och v�rmeverk
109                         35 el-, gas- och v�rmeverk
110                         35 el-, gas- och v�rmeverk
111                         35 el-, gas- och v�rmeverk

                                            bransletyp 2009K1 2009K2 2009K3  \
0                                    eldningsolja nr 1   2137   1434   1169
1                                  eldningsolja nr 2-6   7819   5127   4512
2                                              stenkol   3938   3980   3089
3                                                 koks   6584   5555   2839
4    tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...  46553  44881  43536
..                                                 ...    ...    ...    ...
107                                            stenkol   3494   1413    109
108                                               koks     ..     ..     ..
109  tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...  74702  38492  25783
110                                           naturgas   9328   2600   2421
111                                   propan och butan    291     77     85

    2009K4 2010K1 2010K2 2010K3 2010K4  ... 2020K1 2020K2 2020K3 2020K4  \
0     1778   2262   1532   1186   2154  ...    896    794    781    907
1     5984   8246   5224   4742   6928  ...   2244   2098   1920   2190
2     5205   5696   5711   5447   6129  ...   4723   4580   4288   5846
3     9315  10994  11000   9985   9515  ...   9093   8591   6551   9038
4    48155  49893  44930  45945  54049  ...  53171  49344  43353  48557
..     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...
107   4314   5144   1772     25   4969  ...     ..     ..     ..     12
108     ..     ..     ..     ..     ..  ...     ..     ..     ..     ..
109  64637  82576  41459  27912  71821  ...  72003  42506  31384  60518
110   9901  15774   6594   3297  12708  ...    326    150    506    328
111    248    489     87     98    301  ...     ..     ..      8      8

    2021K1 2021K2 2021K3 2021K4 2022K1 2022k2
0      995    851    772    907    774    847
1     2268   1997   1922   2013   1847   1698
2     5304   5162   4184   5363   4991   3925
3     8761   8723   7146   9024   8794   9122
4    49600  44459  44220  49428  49780  47056
..     ...    ...    ...    ...    ...    ...
107    122     ..     ..    105     54     ..
108     ..     ..     ..     ..     ..     ..
109  81871  45448  32786  74255  81323  49574
110   2100    128     89   1415    854    213
111     25      9      8     36     22     12

[112 rows x 56 columns]>
SNI2007       object
bransletyp    object
2009K1        object
2009K2        object
2009K3        object
2009K4        object
2010K1        object
2010K2        object
2010K3        object
2010K4        object
2011K1        object
2011K2        object
2011K3        object
2011K4        object
2012K1        object
2012K2        object
2012K3        object
2012K4        object
2013K1        object
2013K2        object
2013K3        object
2013K4        object
2014K1        object
2014K2        object
2014K3        object
2014K4        object
2015K1        object
2015K2        object
2015K3        object
2015K4        object
2016K1        object
2016K2        object
2016K3        object
2016K4        object
2017K1        object
2017K2        object
2017K3        object
2017K4        object
2018K1        object
2018K2        object
2018K3        object
2018K4        object
2019K1        object
2019K2        object
2019K3        object
2019K4        object
2020K1        object
2020K2        object
2020K3        object
2020K4        object
2021K1        object
2021K2        object
2021K3        object
2021K4        object
2022K1        object
2022k2        object
dtype: object

In [28]:
# bränsleanvändning, terajoule (TJ) efter näringsgren SNI92, bränsletyp och kvartal
# industry type & fuel type & quarter 
df24 = pd.read_table(
    '../data/grouped-data/branslefarbrukning-SNI92-per-kvartal.csv', sep=',')

print(df24.columns)

df24.rename(columns={'n�ringsgren SNI92': 'SNI92', 'br�nsletyp': 'bransletyp'}, inplace=True)

print('SNI92\n', df24.SNI92.drop_duplicates(keep='first').reset_index(drop=True))
print('bransletyp\n', df24.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))


print(df24.describe)

print(df24.dtypes)

Index(['n�ringsgren SNI92', 'br�nsletyp', '2002K1', '2002K2', '2002K3',
       '2002K4', '2003K1', '2003K2', '2003K3', '2003K4', '2004K1', '2004K2',
       '2004K3', '2004K4', '2005K1', '2005K2', '2005K3', '2005K4', '2006K1',
       '2006K2', '2006K3', '2006K4', '2007K1', '2007K2', '2007K3', '2007K4',
       '2008K1', '2008K2', '2008K3', '2008K4', '2009K1', '2009K2', '2009K3',
       '2009K4'],
      dtype='object')
SNI92
 0       C+D utvinning av mineral, tillverkningsindustri
1                     C gruvor och mineralutvinningsind
2          15+16 livsmedels-, dryckesvaru-, o tobaksind
3     17-19 textil-, bekl�dnads-, l�der- o l�dervaruind
4     20 ind f tr� o varor av tr�, kork, rotting, ej...
5     21+22 massa- o pappersindustri; F�rlag och gra...
6     23.1+23.3+24 stenkolsprod, k�rnbr�nsle; kemisk...
7                       25 gummi- och plastvaruindustri
8                         26 jord- och stenvaruindustri
9                               27 st�l- och metallverk
10    27.1-27.3 j�rn- och st�lverk; prim�rbearbetnin...
11    28 industri f�r metallvaror utom maskiner och ...
12      29 maskinindustri som ej ing�r i annan underavd
13            30-33 industri f�r el- och optikprodukter
14                        34+35 transportmedelsindustri
15                    36+37 �vrig tillverkningsindustri
16                           40 el-, gas- och v�rmeverk
Name: SNI92, dtype: object
bransletyp
 0                                    eldningsolja nr 1
1                                  eldningsolja nr 2-6
2                                              stenkol
3                                                 koks
4    tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...
5                                             naturgas
6                                     propan och butan
Name: bransletyp, dtype: object
<bound method NDFrame.describe of                                                SNI92  \
0    C+D utvinning av mineral, tillverkningsindustri
1    C+D utvinning av mineral, tillverkningsindustri
2    C+D utvinning av mineral, tillverkningsindustri
3    C+D utvinning av mineral, tillverkningsindustri
4    C+D utvinning av mineral, tillverkningsindustri
..                                               ...
114                       40 el-, gas- och v�rmeverk
115                       40 el-, gas- och v�rmeverk
116                       40 el-, gas- och v�rmeverk
117                       40 el-, gas- och v�rmeverk
118                       40 el-, gas- och v�rmeverk

                                            bransletyp 2002K1 2002K2 2002K3  \
0                                    eldningsolja nr 1   3378   2330   2006
1                                  eldningsolja nr 2-6  10858   8311   7237
2                                              stenkol   6482   6576   5776
3                                                 koks  10652  11014   9119
4    tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...  45784  41604  39652
..                                                 ...    ...    ...    ...
114                                            stenkol   5824    877    730
115                                               koks     ..     ..     ..
116  tr�dbr�nslen, avlutar, tall-, beckolja, bioolj...  44578  22438  14293
117                                           naturgas   6006   1138    660
118                                   propan och butan    519     69     78

    2002K4 2003K1 2003K2 2003K3 2003K4  ... 2007K3 2007K4 2008K1 2008K2  \
0     3605   4456   2524   2066   3104  ...   1581   2304   2022   1601
1    12642  13799   9118   8218  11651  ...   6708   8583   7441   6219
2     6561   6118   6239   5564   6137  ...   6341   7096   6755   7620
3    11737  10711  10678  11568  11082  ...   9117  11052  11934  11347
4    41354  43692  44576  41060  45925  ...  45632  50143  46113  47387
..     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...
114   7638   8261   4077   1242   5265  ...    477   3777   3652   1082
115     ..     ..     ..     ..     ..  ...     ..     ..     ..     ..
116  50575  49792  27436  16409  45817  ...  22574  57804  69839  36083
117   6537   8184   1274    420   3940  ...    327   5469   6017    889
118    559    488     95    163    221  ...     44     48    104     34

    2008K3 2008K4 2009K1 2009K2 2009K3 2009K4
0     1365   1827   2137   1434   1169   1778
1     6131   7596   7913   5216   4571   6033
2     6521   6008   3938   3980   3089   5205
3    10338   9960   6584   5555   2839   9315
4    49392  45492  46553  44881  43536  48155
..     ...    ...    ...    ...    ...    ...
114    507   3903   3494   1413    109   4314
115     ..     ..     ..     ..     ..     ..
116  26443  60995  74702  38492  25783  64637
117    501   4413   9328   2600   2421   9901
118     45    176    291     77     85    248

[119 rows x 34 columns]>
SNI92         object
bransletyp    object
2002K1        object
2002K2        object
2002K3        object
2002K4        object
2003K1        object
2003K2        object
2003K3        object
2003K4        object
2004K1        object
2004K2        object
2004K3        object
2004K4        object
2005K1        object
2005K2        object
2005K3        object
2005K4        object
2006K1        object
2006K2        object
2006K3        object
2006K4        object
2007K1        object
2007K2        object
2007K3        object
2007K4        object
2008K1        object
2008K2        object
2008K3        object
2008K4        object
2009K1        object
2009K2        object
2009K3        object
2009K4        object
dtype: object

In [29]:
# Leveranser av flytande bränslen samt gasol, m3 och ton efter varuslag, färbrukarkategori och månad
# & month
df25 = pd.read_table('../data/grouped-data/leveranser-per-manad.csv', sep=',')

print(df25.columns)

df25.rename(columns={'f�rbrukarkategori': 'forbrukarkategori'}, inplace=True)

print('forbrukarkategori\n', df25.forbrukarkategori.drop_duplicates(keep='first').reset_index(drop=True))


print(df25.describe)

print(df25.dtypes)

Index(['varuslag', 'f�rbrukarkategori', '1997M01', '1997M02', '1997M03',
       '1997M04', '1997M05', '1997M06', '1997M07', '1997M08',
       ...
       '2017M03', '2017M04', '2017M05', '2017M06', '2017M07', '2017M08',
       '2017M09', '2017M10', '2017M11', '2017M12'],
      dtype='object', length=254)
forbrukarkategori
 0              totalt exkl bunkring f�r utrikes sj�fart
1                                        �terf�rs�ljare
2                                           konsumenter
3                          bunkring f�r utrikes sj�fart
4                            jordbruk, skogsbruk, fiske
5       gruvor och mineralbrott, tillverkningsindustrin
6                                    kraftverk, gasverk
7                             kraftv�rmeverk, v�rmeverk
8     �vrigt inom stat, kommun, landsting eller f�re...
9                                             j�rnv�gar
10       sj�fart exklusive bunkring f�r utrikes sj�fart
11                                en- och tv�bostadshus
12                                       flerbostadshus
13                                   �vriga fastigheter
14                                               �vrigt
Name: forbrukarkategori, dtype: object
<bound method NDFrame.describe of                                            varuslag  \
0    l�ttbensin (f�r framst�llning av stadsgas), m3
1    l�ttbensin (f�r framst�llning av stadsgas), m3
2    l�ttbensin (f�r framst�llning av stadsgas), m3
3    l�ttbensin (f�r framst�llning av stadsgas), m3
4                                    flygbensin, m3
..                                              ...
131   annan propan och butan (gasol) i flaskor, ton
132   annan propan och butan (gasol) i flaskor, ton
133   annan propan och butan (gasol) i flaskor, ton
134   annan propan och butan (gasol) i flaskor, ton
135   annan propan och butan (gasol) i flaskor, ton

                                  forbrukarkategori 1997M01 1997M02 1997M03  \
0          totalt exkl bunkring f�r utrikes sj�fart    7290       0    7259
1                                    �terf�rs�ljare       0       0       0
2                                       konsumenter       0       0       0
3                      bunkring f�r utrikes sj�fart       0       0       0
4          totalt exkl bunkring f�r utrikes sj�fart     338     361     381
..                                              ...     ...     ...     ...
131  sj�fart exklusive bunkring f�r utrikes sj�fart       0       0       0
132                           en- och tv�bostadshus       0       0       0
133                                  flerbostadshus       0       0       0
134                              �vriga fastigheter       0       0       0
135                                          �vrigt     847     805     755

    1997M04 1997M05 1997M06 1997M07 1997M08  ... 2017M03 2017M04 2017M05  \
0      3816       0    7137   13128       0  ...       0       0       0
1         0       0       0       0       0  ...       0       0       0
2         0       0       0   13128       0  ...       0       0       0
3         0       0       0       0       0  ...       0       0       0
4       609     724     940     909     886  ...     142      ..     255
..      ...     ...     ...     ...     ...  ...     ...     ...     ...
131       0       0       0       0       0  ...       0       0       0
132       0       0       0       0       0  ...       0       0       0
133       0       0       0       0       0  ...       0       0       0
134       0       0       0       0       0  ...       0       0       0
135     803    1203    1683    1142     927  ...     890     475    1568

    2017M06 2017M07 2017M08 2017M09 2017M10 2017M11 2017M12
0         0       0       0       0       0       0       0
1         0       0       0       0       0       0       0
2         0       0       0       0       0       0       0
3         0       0       0       0       0       0       0
4        ..     215     261      ..     148     116      63
..      ...     ...     ...     ...     ...     ...     ...
131       0       0       0       0       0       0       0
132       0       0       0       0       0       0       0
133       0       0       0       0       0       0       0
134       0       0       0       0       0       0       0
135    1595    1434    1296     831     762     864     757

[136 rows x 254 columns]>
varuslag             object
forbrukarkategori    object
1997M01              object
1997M02              object
1997M03              object
                      ...
2017M08              object
2017M09              object
2017M10              object
2017M11              object
2017M12              object
Length: 254, dtype: object

In [30]:
# Elfärbrukning inom utvinning av mineral, tillverkningsindustri, GWh efter näringsgren SNI92 och månad
# industry type & month
df26 = pd.read_table(
    '../data/grouped-data/elfarbrukning-per-manad.csv', sep=',')

print(df26.columns)

df26.rename(columns={'n�ringsgren SNI92': 'SNI92'}, inplace=True)

print('SNI92\n', df26.SNI92.drop_duplicates(keep='first').reset_index(drop=True))


print(df26.describe)

print(df26.dtypes)

Index(['n�ringsgren SNI92', '1990M01', '1990M02', '1990M03', '1990M04',
       '1990M05', '1990M06', '1990M07', '1990M08', '1990M09',
       ...
       '2009M03', '2009M04', '2009M05', '2009M06', '2009M07', '2009M08',
       '2009M09', '2009M10', '2009M11', '2009M12'],
      dtype='object', length=241)
SNI92
 0       C+D utvinning av mineral, tillverkningsindustri
1          10-37DiffEl ej branschf�rdelad elf�rbrukning
2              10-37SumEl branschf�rdelad elf�rbrukning
3                 10-14 gruvor och mineralutvinningsind
4                       10+11+14 annan mineralutvinning
5                                  13.1 j�rnmalmsgruvor
6                          13.2 andra metallmalmsgruvor
7          15+16 livsmedels-, dryckesvaru-, o tobaksind
8     17-19 textil-, bekl�dnads-, l�der- o l�dervaruind
9     20 ind f tr� o varor av tr�, kork, rotting, ej...
10     20.1 s�gverk och hyvlerier; tr�impregneringsverk
11    20.2-20.5 annan tr�industri o varor av tr� m.m...
12          21 massa-, pappers- och pappersvaruindustri
13                                  21.11 massaindustri
14                      21.12 pappers- och pappindustri
15             21.2 industri f�r pappers- och pappvaror
16    22 f�rlag; grafisk och annan reproduktionsindu...
17    23+24 kemisk ind; stenkolsprod, raff petroleum...
18    23 ind f stenkolsprod, raff petroleumprod o k�...
19                                   24 kemisk industri
20                            24.1 baskemikalieindustri
21                      25 gummi- och plastvaruindustri
22                        26 jord- och stenvaruindustri
23                              27 st�l- och metallverk
24    27.1-27.3 j�rn- och st�lverk; prim�rbearbetnin...
25    27.4+27.5 andra metallverk; j�rn- o metallgjut...
26    28 industri f�r metallvaror utom maskiner och ...
27      29 maskinindustri som ej ing�r i annan underavd
28            30-33 industri f�r el- och optikprodukter
29            30 industri f�r kontorsmaskiner o datorer
30                             31 annan elektroindustri
31                               32 teleproduktindustri
32    33 ind f precisions-, medicinska o optiska ins...
33                        34+35 transportmedelsindustri
34    34 industri f�r motorfordon, sl�pfordon o p�h�...
35                     35 annan transportmedelsindustri
36                    36+37 �vrig tillverkningsindustri
Name: SNI92, dtype: object
<bound method NDFrame.describe of                                                 SNI92 1990M01 1990M02 1990M03  \
0     C+D utvinning av mineral, tillverkningsindustri    4874    4459    4918
1        10-37DiffEl ej branschf�rdelad elf�rbrukning     252     260     252
2            10-37SumEl branschf�rdelad elf�rbrukning    4622    4199    4666
3               10-14 gruvor och mineralutvinningsind     227     196     221
4                     10+11+14 annan mineralutvinning      ..      ..      ..
5                                13.1 j�rnmalmsgruvor     141     120     132
6                        13.2 andra metallmalmsgruvor      69      60      72
7        15+16 livsmedels-, dryckesvaru-, o tobaksind     226     202     233
8   17-19 textil-, bekl�dnads-, l�der- o l�dervaruind      45      39      43
9   20 ind f tr� o varor av tr�, kork, rotting, ej...     181     168     179
10   20.1 s�gverk och hyvlerier; tr�impregneringsverk      95      92      99
11  20.2-20.5 annan tr�industri o varor av tr� m.m...      86      77      80
12        21 massa-, pappers- och pappersvaruindustri    1704    1579    1792
13                                21.11 massaindustri     333     309     337
14                    21.12 pappers- och pappindustri    1350    1252    1435
15           21.2 industri f�r pappers- och pappvaror      20      18      21
16  22 f�rlag; grafisk och annan reproduktionsindu...      58      50      50
17  23+24 kemisk ind; stenkolsprod, raff petroleum...     543     506     540
18  23 ind f stenkolsprod, raff petroleumprod o k�...      52      48      54
19                                 24 kemisk industri     491     458     486
20                          24.1 baskemikalieindustri     438     407     433
21                    25 gummi- och plastvaruindustri      86      78      85
22                      26 jord- och stenvaruindustri     120     115     128
23                            27 st�l- och metallverk     708     624     683
24  27.1-27.3 j�rn- och st�lverk; prim�rbearbetnin...     492     425     457
25  27.4+27.5 andra metallverk; j�rn- o metallgjut...     216     199     226
26  28 industri f�r metallvaror utom maskiner och ...     164     149     163
27    29 maskinindustri som ej ing�r i annan underavd     186     158     174
28          30-33 industri f�r el- och optikprodukter     123     104     120
29          30 industri f�r kontorsmaskiner o datorer       7       5       7
30                           31 annan elektroindustri      71      62      68
31                             32 teleproduktindustri      32      26      32
32  33 ind f precisions-, medicinska o optiska ins...      13      11      13
33                      34+35 transportmedelsindustri     213     194     215
34  34 industri f�r motorfordon, sl�pfordon o p�h�...     165     152     168
35                   35 annan transportmedelsindustri      48      42      46
36                  36+37 �vrig tillverkningsindustri      38      37      40

   1990M04 1990M05 1990M06 1990M07 1990M08 1990M09  ... 2009M03 2009M04  \
0     4409    4482    4162    3271    4478    4310  ...    4297    3938
1      239     224     221     137     214     227  ...      90      81
2     4170    4258    3941    3134    4264    4083  ...    4207    3857
3      199     194     164     140     180     178  ...     211     208
4       ..      ..      ..      ..      ..      ..  ...      24      20
5      125     123      97      94     112     110  ...     121     125
6       61      58      55      38      56      56  ...      66      62
7      211     225     209     201     238     221  ...     207     198
8       39      41      37      21      42      41  ...      18      16
9      157     160     145      59     143     152  ...     197     177
10      87      85      84      39      76      85  ...     153     139
11      71      75      60      20      67      67  ...      44      39
12    1622    1635    1463    1464    1658    1556  ...    1763    1651
13     320     314     290     270     290     286  ...     284     270
14    1285    1304    1156    1185    1348    1252  ...    1423    1334
15      17      17      18       9      20      18  ...      56      47
16      48      46      42      37      49      44  ...      47      42
17     480     504     528     436     514     461  ...     527     489
18      55      52      65      52      58      52  ...      82      76
19     425     452     463     384     456     409  ...     445     414
20     376     402     415     349     405     362  ...     381     350
21      67      77      66      29      77      75  ...      97      87
22     114     113     109      75     111     110  ...      86      79
23     624     650     600     354     631     614  ...     484     425
24     415     441     387     169     411     416  ...     291     243
25     209     210     213     185     220     198  ...     194     182
26     135     136     125      57     132     137  ...     146     122
27     147     144     135      74     143     150  ...     133     111
28     108     109     105      69     107     107  ...      83      74
29       9       8       7       3       4       8  ...       1       1
30      59      60      57      39      62      60  ...      46      39
31      28      29      30      19      28      28  ...      16      15
32      11      12      11       8      13      11  ...      19      18
33     187     190     185     107     200     201  ...     168     142
34     143     150     145      81     162     160  ...     139     117
35      44      40      40      26      38      41  ...      29      25
36      32      34      28      11      39      36  ...      42      37

   2009M05 2009M06 2009M07 2009M08 2009M09 2009M10 2009M11 2009M12
0     4154    4157    3396    4126    4198    4390    4455    4324
1       79      83      56      80      88      91      89      85
2     4075    4074    3340    4046    4110    4299    4366    4240
3      203     154     125     218     212     267     336     234
4       16      15       8      18      18      20      17      18
5      124      78      62     138     132     179     254     145
6       63      62      55      62      62      68      65      71
7      199     202     202     219     219     219     217     207
8       16      15       8      14      15      16      16      15
9      172     178      92     155     185     194     190     179
10     132     139      72     116     142     150     147     140
11      39      39      20      38      43      44      43      38
12    1852    1847    1721    1836    1753    1795    1776    1805
13     260     281     258     271     263     271     260     276
14    1540    1516    1414    1512    1438    1469    1463    1477
15      52      50      49      53      52      55      53      53
16      41      40      37      41      42      44      43      43
17     506     489     432     496     466     503     534     542
18      82      77      77      80      73      78      82      84
19     424     411     355     417     393     426     452     458
20     360     348     298     351     328     359     388     397
21      90      93      57      88      97      98      94      83
22      85      81      61      79      85      83      88      84
23     431     461     273     419     494     511     517     527
24     256     272      95     220     291     304     315     323
25     175     189     178     199     202     207     202     204
26     119     128      73     121     134     145     143     135
27     108     112      71     106     116     121     119     114
28      72      74      59      72      75      79      76      78
29       1       1       1       1       1       1       1       1
30      38      40      28      37      40      44      41      42
31      15      15      14      15      15      15      15      16
32      18      18      16      18      19      19      18      18
33     145     160     109     143     174     178     175     155
34     121     135      89     121     151     153     149     129
35      25      24      20      23      23      25      25      27
36      36      40      19      39      43      44      42      38

[37 rows x 241 columns]>
SNI92      object
1990M01    object
1990M02    object
1990M03    object
1990M04    object
            ...
2009M08     int64
2009M09     int64
2009M10     int64
2009M11     int64
2009M12     int64
Length: 241, dtype: object

In [31]:
# Eltillfärsel netto, GWh efter produktionsslag och månad
# & month
df27 = pd.read_table(
    '../data/grouped-data/eltillfarsel-per-manad.csv', sep=',')

print(df27.columns)

df27.rename(columns={'anv�ndningsomr�de': 'anvandningsomrade'}, inplace=True)

print('anvandningsomrade\n', df27.anvandningsomrade.drop_duplicates(keep='first').reset_index(drop=True))

print(df27.describe)

print(df27.dtypes)

Index(['anv�ndningsomr�de', '1990M01', '1990M02', '1990M03', '1990M04',
       '1990M05', '1990M06', '1990M07', '1990M08', '1990M09',
       ...
       '2021M12', '2022M01', '2022M02', '2022M03', '2022M04', '2022M05',
       '2022M06', '2022M07', '2022M08', '2022M09'],
      dtype='object', length=394)
anvandningsomrade
 0                     summa f�rbrukad el
1                                 export
2                f�rbrukning inom landet
3     mineralutvinning och tillverkning
4     el-, gas-,  v�rme- och vattenverk
5        j�rn- och sp�rv�gar, busstrafik
6                 bost�der, service m.m.
7         bost�der, temperaturkorrigerat
8                              f�rluster
9                      stamn�tsf�rluster
10      f�rluster exkl stamn�tsf�rluster
Name: anvandningsomrade, dtype: object
<bound method NDFrame.describe of                      anvandningsomrade  1990M01  1990M02  1990M03  1990M04  \
0                   summa f�rbrukad el    15249    13211    14548    12803
1                               export      594      891     1360     1415
2              f�rbrukning inom landet    14655    12320    13188    11388
3   mineralutvinning och tillverkning      4874     4459     4918     4408
4   el-, gas-,  v�rme- och vattenverk       937      933     1054      947
5      j�rn- och sp�rv�gar, busstrafik      239      210      235      200
6               bost�der, service m.m.     7468     5897     6048     5112
7       bost�der, temperaturkorrigerat     8267     7285     6962     5675
8                            f�rluster     1137      821      933      721
9                    stamn�tsf�rluster      236      184      208      182
10    f�rluster exkl stamn�tsf�rluster      901      637      725      539

    1990M05  1990M06  1990M07  1990M08  1990M09  ...  2021M12  2022M01  \
0     11845    10312     9590    10986    12219  ...    18123    17657
1      1535     1431     1517     1549     1550  ...     3022     3350
2     10310     8881     8073     9437    10669  ...    15101    14307
3      4482     4161     3272     4478     4309  ...     4101     4149
4       756      617      517      590      807  ...      416      442
5       209      178      157      178      201  ...      283      268
6      4241     3420     3666     3638     4709  ...     9155     8387
7      4535     3488     3677     3675     4489  ...     8914     8987
8       622      505      461      553      643  ...     1146     1061
9       184      183      199      194      183  ...      453      433
10      438      322      262      359      460  ...      693      628

    2022M02  2022M03  2022M04  2022M05  2022M06  2022M07  2022M08  2022M09
0     15740    16447    14286    13432    12679    13425    13462    12352
1      2867     3306     2795     3230     3363     4404     3928     2714
2     12873    13141    11491    10202     9316     9021     9534     9638
3      3890     4174     3779     3925     3856     3602     3774     3632
4       422      387      289      191      187      188      200      209
5       247      265      236      221      206      195      208      215
6      7324     7324     6367     5132     4367     4296     4572     4848
7      7881     7730     6310     5193     4677     4330     4756     4805
8       990      991      820      733      700      740      780      734
9       433      455      376      374      378      420      472      391
10      557      536      444      359      322      320      308      343

[11 rows x 394 columns]>
anvandningsomrade    object
1990M01               int64
1990M02               int64
1990M03               int64
1990M04               int64
                      ...
2022M05               int64
2022M06               int64
2022M07               int64
2022M08               int64
2022M09               int64
Length: 394, dtype: object

In [32]:
# Elanvändning, GWh efter användningsområde och månad
# & month
df28 = pd.read_table(
    '../data/grouped-data/eltillfarsel-per-manad.csv', sep=',')

# print(df28.columns)

df28.rename(columns={'anv�ndningsomr�de': 'anvandningsomrade'}, inplace=True)

print('anvandningsomrade\n', df28.anvandningsomrade.drop_duplicates(keep='first').reset_index(drop=True))


print(df28.describe)

print(df28.dtypes)

anvandningsomrade
 0                     summa f�rbrukad el
1                                 export
2                f�rbrukning inom landet
3     mineralutvinning och tillverkning
4     el-, gas-,  v�rme- och vattenverk
5        j�rn- och sp�rv�gar, busstrafik
6                 bost�der, service m.m.
7         bost�der, temperaturkorrigerat
8                              f�rluster
9                      stamn�tsf�rluster
10      f�rluster exkl stamn�tsf�rluster
Name: anvandningsomrade, dtype: object
<bound method NDFrame.describe of                      anvandningsomrade  1990M01  1990M02  1990M03  1990M04  \
0                   summa f�rbrukad el    15249    13211    14548    12803
1                               export      594      891     1360     1415
2              f�rbrukning inom landet    14655    12320    13188    11388
3   mineralutvinning och tillverkning      4874     4459     4918     4408
4   el-, gas-,  v�rme- och vattenverk       937      933     1054      947
5      j�rn- och sp�rv�gar, busstrafik      239      210      235      200
6               bost�der, service m.m.     7468     5897     6048     5112
7       bost�der, temperaturkorrigerat     8267     7285     6962     5675
8                            f�rluster     1137      821      933      721
9                    stamn�tsf�rluster      236      184      208      182
10    f�rluster exkl stamn�tsf�rluster      901      637      725      539

    1990M05  1990M06  1990M07  1990M08  1990M09  ...  2021M12  2022M01  \
0     11845    10312     9590    10986    12219  ...    18123    17657
1      1535     1431     1517     1549     1550  ...     3022     3350
2     10310     8881     8073     9437    10669  ...    15101    14307
3      4482     4161     3272     4478     4309  ...     4101     4149
4       756      617      517      590      807  ...      416      442
5       209      178      157      178      201  ...      283      268
6      4241     3420     3666     3638     4709  ...     9155     8387
7      4535     3488     3677     3675     4489  ...     8914     8987
8       622      505      461      553      643  ...     1146     1061
9       184      183      199      194      183  ...      453      433
10      438      322      262      359      460  ...      693      628

    2022M02  2022M03  2022M04  2022M05  2022M06  2022M07  2022M08  2022M09
0     15740    16447    14286    13432    12679    13425    13462    12352
1      2867     3306     2795     3230     3363     4404     3928     2714
2     12873    13141    11491    10202     9316     9021     9534     9638
3      3890     4174     3779     3925     3856     3602     3774     3632
4       422      387      289      191      187      188      200      209
5       247      265      236      221      206      195      208      215
6      7324     7324     6367     5132     4367     4296     4572     4848
7      7881     7730     6310     5193     4677     4330     4756     4805
8       990      991      820      733      700      740      780      734
9       433      455      376      374      378      420      472      391
10      557      536      444      359      322      320      308      343

[11 rows x 394 columns]>
anvandningsomrade    object
1990M01               int64
1990M02               int64
1990M03               int64
1990M04               int64
                      ...
2022M05               int64
2022M06               int64
2022M07               int64
2022M08               int64
2022M09               int64
Length: 394, dtype: object

In [33]:
# Elfärbrukning inom utvinning av mineral, tillverkningsindustri, GWh efter näringsgren SNI69 och månad
# industry type & month
df29 = pd.read_table(
    '../data/grouped-data/elfarbrukning-mineral-per-manad.csv', sep=',')

print(df29.columns)

df29.rename(columns={'n�ringsgren SNI69': 'SNI69'}, inplace=True)

print('SNI69\n', df29.SNI69.drop_duplicates(keep='first').reset_index(drop=True))

print(df29.describe)

print(df29.dtypes)

Index(['n�ringsgren SNI69', '1974M01', '1974M02', '1974M03', '1974M04',
       '1974M05', '1974M06', '1974M07', '1974M08', '1974M09',
       ...
       '1989M03', '1989M04', '1989M05', '1989M06', '1989M07', '1989M08',
       '1989M09', '1989M10', '1989M11', '1989M12'],
      dtype='object', length=193)
SNI69
 0               gruvor o mineralbrott,tillverkn ind
1          ej branschf�rdelad tillverkningsindustri
2     summa branschf�rdelat enl industristatistiken
3                             gruvor o mineralbrott
4                                        malmgruvor
5                                   j�rnmalmsgruvor
6                             tillverkningsindustri
7              livsmedels-,dryckesvaru- o tobaksind
8                                livsmedelsindustri
9                               dryckesvaruindustri
10                                   tobaksindustri
11                     textil-,bekl�dnads-,l�derind
12                                  tr�varuindustri
13                s�gverk,hyvlerier,tr�impregn verk
14                      massa-,pappers-,grafisk ind
15                 massa-,pappers- o pappersvaruind
16                                    massaindustri
17              mekanisk-, halvkemisk massaindustri
18                  sulfat- och sulfitmassaindustri
19                          pappers- o pappindustri
20                            tr�fiberplattindustri
21              grafisk produktion, f�rlagsverksamh
22                              kemisk industri m m
23                kemikalie-,g�dselmedels-,plastind
24                            annan kemisk industri
25                           petroleumraffinaderier
26               sm�rjmedels-,asfalt- o kolprod ind
27                                gummivaruindustri
28                                plastvaruindustri
29                         jord- o stenvaruindustri
30                tegel-,cement- o a mineralvaruind
31                                   cementindustri
32                         j�rn-,st�l- o metallverk
33                 j�rn-,st�l- o ferrolegeringsverk
34                j�rn- och st�lverk, j�rngjuterier
35                               ferrolegeringsverk
36                               ickej�rnmetallverk
37                                verkstadsindustri
38                               metallvaruindustri
39                                   maskinindustri
40                                  elektroindustri
41                          transportmedelsindustri
42                          skeppsvarv,b�tbyggerier
43                 ind f�r instrument,foto,optik,ur
44                      verkstadsindustri exkl varv
45                         annan tillverkn industri
Name: SNI69, dtype: object
<bound method NDFrame.describe of                                             SNI69 1974M01 1974M02 1974M03  \
0             gruvor o mineralbrott,tillverkn ind    3368    3154    3479
1        ej branschf�rdelad tillverkningsindustri     126     119     129
2   summa branschf�rdelat enl industristatistiken    3242    3035    3350
3                           gruvor o mineralbrott     183     175     199
4                                      malmgruvor      ..      ..      ..
5                                 j�rnmalmsgruvor     132     127     144
6                           tillverkningsindustri      ..      ..      ..
7            livsmedels-,dryckesvaru- o tobaksind      93      86      96
8                              livsmedelsindustri      ..      ..      ..
9                             dryckesvaruindustri      ..      ..      ..
10                                 tobaksindustri      ..      ..      ..
11                   textil-,bekl�dnads-,l�derind      36      33      35
12                                tr�varuindustri     121     113     124
13              s�gverk,hyvlerier,tr�impregn verk      ..      ..      ..
14                    massa-,pappers-,grafisk ind    1139    1058    1182
15               massa-,pappers- o pappersvaruind      ..      ..      ..
16                                  massaindustri      ..      ..      ..
17            mekanisk-, halvkemisk massaindustri      75      73      78
18                sulfat- och sulfitmassaindustri     345     300     338
19                        pappers- o pappindustri     646     617     690
20                          tr�fiberplattindustri      42      40      45
21            grafisk produktion, f�rlagsverksamh      ..      ..      ..
22                            kemisk industri m m     477     454     484
23              kemikalie-,g�dselmedels-,plastind      ..      ..      ..
24                          annan kemisk industri      ..      ..      ..
25                         petroleumraffinaderier      ..      ..      ..
26             sm�rjmedels-,asfalt- o kolprod ind      ..      ..      ..
27                              gummivaruindustri      ..      ..      ..
28                              plastvaruindustri      ..      ..      ..
29                       jord- o stenvaruindustri     103      97     111
30              tegel-,cement- o a mineralvaruind      ..      ..      ..
31                                 cementindustri      31      31      35
32                       j�rn-,st�l- o metallverk     727     676     750
33               j�rn-,st�l- o ferrolegeringsverk      ..      ..      ..
34              j�rn- och st�lverk, j�rngjuterier     424     404     445
35                             ferrolegeringsverk     109      92     106
36                             ickej�rnmetallverk     194     180     199
37                              verkstadsindustri     360     341     366
38                             metallvaruindustri      94      91      98
39                                 maskinindustri     113     104     112
40                                elektroindustri      59      57      60
41                        transportmedelsindustri      ..      ..      ..
42                        skeppsvarv,b�tbyggerier      25      24      24
43               ind f�r instrument,foto,optik,ur      ..      ..      ..
44                    verkstadsindustri exkl varv      69      65      72
45                       annan tillverkn industri       3       2       3

   1974M04 1974M05 1974M06 1974M07 1974M08 1974M09  ... 1989M03 1989M04  \
0     3189    3373    2940    2571    3324    3417  ...    4853    4648
1      124     125     112      72     125     131  ...     229     211
2     3065    3248    2828    2499    3199    3286  ...    4624    4437
3      188     188     170     130     190     186  ...     214     191
4       ..      ..      ..      ..      ..      ..  ...     206     184
5      136     132     122      99     136     134  ...     139     121
6       ..      ..      ..      ..      ..      ..  ...    4410    4246
7       93      99      88      86     104     115  ...     217     207
8       ..      ..      ..      ..      ..      ..  ...     192     185
9       ..      ..      ..      ..      ..      ..  ...      23      20
10      ..      ..      ..      ..      ..      ..  ...       2       2
11      33      33      29      13      35      35  ...      37      35
12     111     110      89      49      93     109  ...     192     177
13      ..      ..      ..      ..      ..      ..  ...     111     102
14    1040    1158     988    1092    1158    1150  ...    1770    1791
15      ..      ..      ..      ..      ..      ..  ...    1732    1755
16      ..      ..      ..      ..      ..      ..  ...     381     372
17      68      77      65      68      75      74  ...      56      60
18     316     318     283     315     320     312  ...     326     311
19     589     687     577     654     691     690  ...    1298    1328
20      38      46      35      30      41      41  ...      23      23
21      ..      ..      ..      ..      ..      ..  ...      38      36
22     478     481     445     429     491     487  ...     669     618
23      ..      ..      ..      ..      ..      ..  ...     485     445
24      ..      ..      ..      ..      ..      ..  ...      49      47
25      ..      ..      ..      ..      ..      ..  ...      45      42
26      ..      ..      ..      ..      ..      ..  ...       9       8
27      ..      ..      ..      ..      ..      ..  ...      31      29
28      ..      ..      ..      ..      ..      ..  ...      50      47
29     110     110     103      77     103     109  ...     120     117
30      ..      ..      ..      ..      ..      ..  ...      88      86
31      38      38      38      33      34      34  ...      26      25
32     670     719     600     459     663     715  ...     742     687
33      ..      ..      ..      ..      ..      ..  ...     506     458
34     380     423     327     188     387     436  ...     430     403
35     103     101      90     100      86      99  ...      76      55
36     187     195     183     171     190     180  ...     236     229
37     339     348     314     163     359     377  ...     658     610
38      90      98      86      39      99     104  ...     166     152
39     104     104      94      47     106     112  ...     163     146
40      58      59      53      30      62      61  ...     107     104
41      ..      ..      ..      ..      ..      ..  ...     210     198
42      21      21      18      12      20      24  ...      ..      ..
43      ..      ..      ..      ..      ..      ..  ...      12      10
44      66      66      63      35      72      76  ...      ..      ..
45       3       2       2       1       3       3  ...       5       4

   1989M05 1989M06 1989M07 1989M08 1989M09 1989M10 1989M11 1989M12
0     4558    4390    3331    4557    4642    4796    4779    4635
1      203     203     127     203     217     235     234     222
2     4355    4187    3204    4354    4425    4561    4545    4413
3      192     175     126     176     191     207     197     222
4      185     169     123     170     184     200     189     214
5      124     116      83     114     122     137     123     140
6     4163    4012    3078    4178    4234    4354    4348    4191
7      216     213     187     230     233     262     239     213
8      195     194     172     211     211     236     219     192
9       19      17      14      17      20      24      18      19
10       2       2       1       2       2       2       2       2
11      30      34      15      33      39      39      38      32
12     165     170      70     153     172     185     194     181
13      94      97      41      81      95     103     106     103
14    1741    1642    1574    1776    1748    1718    1730    1666
15    1706    1607    1546    1740    1711    1679    1692    1630
16     359     338     306     338     351     347     340     374
17      53      54      39      37      59      51      59      53
18     307     286     268     302     293     297     282     322
19    1293    1213    1218    1351    1303    1275    1295    1206
20      22      21       4      22      23      22      24      20
21      35      35      28      36      37      39      38      36
22     620     602     487     613     620     630     618     650
23     460     436     386     443     444     443     434     476
24      45      48      30      47      47      50      51      50
25      39      40      35      39      45      46      43      47
26       8       8       5       9       8       9       9       9
27      24      25      10      26      27      30      30      25
28      44      45      21      49      49      52      51      43
29     115     107      70     113     110     125     126     116
30      83      75      53      82      79      91      91      85
31      24      19      22      23      23      29      28      25
32     712     666     358     679     699     735     730     708
33     476     436     169     454     470     498     493     468
34     380     354     110     361     384     409     403     365
35      96      82      59      93      86      89      90     103
36     236     230     189     225     229     237     237     240
37     561     574     315     577     609     656     668     621
38     135     142      58     143     150     163     170     154
39     133     136      75     129     140     161     164     152
40     100      98      65     102     107     113     108     101
41     183     187     109     192     201     207     214     203
42      ..      ..      ..      ..      ..      ..      ..      ..
43      10      11       8      11      11      12      12      11
44      ..      ..      ..      ..      ..      ..      ..      ..
45       3       4       2       4       4       4       5       4

[46 rows x 193 columns]>
SNI69      object
1974M01    object
1974M02    object
1974M03    object
1974M04    object
            ...
1989M08    object
1989M09    object
1989M10    object
1989M11    object
1989M12    object
Length: 193, dtype: object

In [34]:
# Byten av elleverantär samt beräknad bytesvolym efter kundkategori, tabellinnehåll och månad
# & month
df30 = pd.read_table(
    '../data/grouped-data/byten-elleverantar-per-manad.csv', sep=',')

print(df30.columns)

print('kundkategori\n', df30.kundkategori.drop_duplicates(keep='first').reset_index(drop=True))

print(df30.describe)

print(df30.dtypes)

Index(['kundkategori', 'Antal byten 2004M04', 'Antal byten 2004M05',
       'Antal byten 2004M06', 'Antal byten 2004M07', 'Antal byten 2004M08',
       'Antal byten 2004M09', 'Antal byten 2004M10', 'Antal byten 2004M11',
       'Antal byten 2004M12',
       ...
       'Bytesvolym, GWh 2021M12', 'Bytesvolym, GWh 2022M01',
       'Bytesvolym, GWh 2022M02', 'Bytesvolym, GWh 2022M03',
       'Bytesvolym, GWh 2022M04', 'Bytesvolym, GWh 2022M05',
       'Bytesvolym, GWh 2022M06', 'Bytesvolym, GWh 2022M07',
       'Bytesvolym, GWh 2022M08', 'Bytesvolym, GWh 2022M09'],
      dtype='object', length=445)
kundkategori
 0                hush�ll/privatpersoner
1    kunder exkl hush�ll/privatpersoner
Name: kundkategori, dtype: object
<bound method NDFrame.describe of                          kundkategori  Antal byten 2004M04  \
0              hush�ll/privatpersoner                20004
1  kunder exkl hush�ll/privatpersoner                 5417

   Antal byten 2004M05  Antal byten 2004M06  Antal byten 2004M07  \
0                25082                17806                22561
1                 7810                 4619                 4734

   Antal byten 2004M08  Antal byten 2004M09  Antal byten 2004M10  \
0                24446                26185                24377
1                 5736                 4562                 4554

   Antal byten 2004M11  Antal byten 2004M12  ...  Bytesvolym, GWh 2021M12  \
0                22642                26682  ...                      590
1                 4233                 6916  ...                     1115

   Bytesvolym, GWh 2022M01  Bytesvolym, GWh 2022M02  Bytesvolym, GWh 2022M03  \
0                      581                      419                      403
1                     1826                      262                      638

   Bytesvolym, GWh 2022M04  Bytesvolym, GWh 2022M05  Bytesvolym, GWh 2022M06  \
0                      442                      429                      407
1                      721                      491                      671

   Bytesvolym, GWh 2022M07  Bytesvolym, GWh 2022M08  Bytesvolym, GWh 2022M09
0                      465                      533                      680
1                      600                      184                      258

[2 rows x 445 columns]>
kundkategori               object
Antal byten 2004M04         int64
Antal byten 2004M05         int64
Antal byten 2004M06         int64
Antal byten 2004M07         int64
                            ...
Bytesvolym, GWh 2022M05     int64
Bytesvolym, GWh 2022M06     int64
Bytesvolym, GWh 2022M07     int64
Bytesvolym, GWh 2022M08     int64
Bytesvolym, GWh 2022M09     int64
Length: 445, dtype: object

In [35]:
# Elfärbrukning inom utvinning av mineral, tillverkningsindustri, GWh efter näringsgren SNI 2007 och månad
# & month
df31 = pd.read_table(
    '../data/grouped-data/elfarbrukning-SNI2007-per-manad.csv', sep=',')

print(df31.columns)

df31.rename(columns={'n�ringsgren SNI 2007': 'SNI2007'}, inplace=True)

print('SNI2007\n', df31.SNI2007.drop_duplicates(keep='first').reset_index(drop=True))

print(df31.describe)

print(df31.dtypes)

Index(['n�ringsgren SNI 2007', '2009M01', '2009M02', '2009M03', '2009M04',
       '2009M05', '2009M06', '2009M07', '2009M08', '2009M09',
       ...
       '2021M12', '2022M01', '2022M02', '2022M03', '2022M04', '2022M05',
       '2022M06', '2022M07', '2022M08', '2022M09'],
      dtype='object', length=166)
SNI2007
 0     B+C tillverkningsindustri; gruvor och mineralu...
1               DiffEL ej branschf�rdelad elf�rbrukning
2     05-33BR branschf�rdelad tillverkningsindustri;...
3            05-09 gruvor och mineralutvinningsindustri
4     10-12 livsmedels-, dryckesvaru- och tobaksindu...
5     13-15 textil-, bekl�dnads-, l�der - och l�derv...
6     16 industri f�r tr� och varor av tr�, kork och...
7     17-18 massa-, pappers- och pappersvaruindustri...
8                                   17.11 massaindustri
9                       17.12 pappers- och pappindustri
10    19-21 kemisk industri, petroleumprodukter och ...
11                      22 gummi- och plastvaruindustri
12    23 industri f�r andra icke-metalliska minerali...
13                              24 st�l- och metallverk
14                          24.1-24.3 j�rn och st�lverk
15    25 industri f�r metallvaror utom maskiner och ...
16    26-28 industri f�r datorer, elektronikvaror, o...
17                        29-30 transportmedelsindustri
18    31-33 �vrig tillverkningsindustri, reparations...
Name: SNI2007, dtype: object
<bound method NDFrame.describe of                                               SNI2007  2009M01  2009M02  \
0   B+C tillverkningsindustri; gruvor och mineralu...     4303     4010
1             DiffEL ej branschf�rdelad elf�rbrukning       85       84
2   05-33BR branschf�rdelad tillverkningsindustri;...     4217     3925
3          05-09 gruvor och mineralutvinningsindustri      224      211
4   10-12 livsmedels-, dryckesvaru- och tobaksindu...      208      192
5   13-15 textil-, bekl�dnads-, l�der - och l�derv...       17       17
6   16 industri f�r tr� och varor av tr�, kork och...      172      179
7   17-18 massa-, pappers- och pappersvaruindustri...     1852     1676
8                                 17.11 massaindustri      283      251
9                     17.12 pappers- och pappindustri     1468     1329
10  19-21 kemisk industri, petroleumprodukter och ...      518      486
11                    22 gummi- och plastvaruindustri       91       92
12  23 industri f�r andra icke-metalliska minerali...       83       77
13                            24 st�l- och metallverk      497      452
14                        24.1-24.3 j�rn och st�lverk      304      277
15  25 industri f�r metallvaror utom maskiner och ...      142      139
16  26-28 industri f�r datorer, elektronikvaror, o...      208      203
17                      29-30 transportmedelsindustri      166      161
18  31-33 �vrig tillverkningsindustri, reparations...       40       40

    2009M03  2009M04  2009M05  2009M06  2009M07  2009M08  2009M09  ...  \
0      4297     3938     4154     4157     3396     4126     4198  ...
1        90       81       79       83       56       80       88  ...
2      4207     3857     4075     4074     3340     4046     4110  ...
3       211      208      203      154      125      218      212  ...
4       207      198      199      202      202      219      219  ...
5        18       16       16       15        8       14       15  ...
6       197      177      172      178       92      155      185  ...
7      1810     1693     1893     1887     1758     1877     1795  ...
8       284      270      260      281      258      271      263  ...
9      1423     1334     1540     1516     1414     1512     1438  ...
10      527      489      506      489      432      496      466  ...
11       97       87       90       93       57       88       97  ...
12       86       79       85       81       61       79       85  ...
13      484      425      431      461      273      419      494  ...
14      291      243      256      272       95      220      291  ...
15      146      122      119      128       73      121      134  ...
16      216      185      180      186      130      178      191  ...
17      168      142      145      160      109      143      174  ...
18       42       37       36       40       19       39       43  ...

    2021M12  2022M01  2022M02  2022M03  2022M04  2022M05  2022M06  2022M07  \
0      4101     4149     3890     4174     3779     3925     3856     3602
1        30       29       28       31       26       28       27       20
2      4071     4120     3862     4143     3753     3897     3829     3582
3       377      361      343      361      334      323      323      345
4       218      202      189      202      179      194      193      183
5        16       17       16       18       15       17       14       10
6       176      172      170      188      161      172      161      107
7      1461     1525     1401     1491     1386     1438     1429     1494
8       315      312      295      303      285      294      304      306
9      1093     1157     1056     1134     1054     1092     1076     1143
10      487      483      451      484      418      432      438      455
11       87       91       90       99       85       92       91       60
12       92       85       81       76       81       90       84       66
13      642      669      625      677      620      633      603      512
14      384      409      386      416      373      398      360      277
15      147      145      138      154      132      140      134       88
16      164      162      157      171      149      157      149      106
17      158      163      158      175      152      165      167      124
18       46       45       43       47       41       44       43       32

    2022M08  2022M09
0      3774     3632
1        25       26
2      3749     3606
3       344      317
4       204      189
5        14       15
6       134      154
7      1418     1335
8       313      283
9      1057     1005
10      472      379
11       82       85
12       74       79
13      569      571
14      322      329
15      118      129
16      141      144
17      138      168
18       41       41

[19 rows x 166 columns]>
SNI2007    object
2009M01     int64
2009M02     int64
2009M03     int64
2009M04     int64
            ...
2022M05     int64
2022M06     int64
2022M07     int64
2022M08     int64
2022M09     int64
Length: 166, dtype: object

In [36]:
# Kvartalsvisa energibalanser, TJ efter energibärare, energiflöden och kvartal
# & quarter
df32 = pd.read_table(
    '../data/grouped-data/energibalanser-per-kvartal.csv', sep=',', low_memory=False)

print(df32.columns)

df32.rename(columns={'energib�rare': 'energibarare', 'energifl�den': 'energifloden'}, inplace=True)

print('energibarare\n', df32.energibarare.drop_duplicates(keep='first').reset_index(drop=True))
print('energifloden\n', df32.energifloden.drop_duplicates(keep='first').reset_index(drop=True))

print(df32.describe)

print(df32.dtypes)

Index(['energib�rare', 'energifl�den', '1984K1', '1984K2', '1984K3', '1984K4',
       '1985K1', '1985K2', '1985K3', '1985K4',
       ...
       '2015K3', '2015K4', '2016K1', '2016K2', '2016K3', '2016K4', '2017K1',
       '2017K2', '2017K3', '2017K4'],
      dtype='object', length=138)
energibarare
 0                                        stenkol
1                                           koks
2                              summa biobr�nslen
3                        r�olja och halvfabrikat
4     petroleumkoks, asfalt, sm�rj- och v�goljor
5                       propan och butan (gasol)
6                                    motorbensin
7      l�ttoljor (exkl motorbensin), mellanoljor
8                                dieselbr�nnolja
9                         tunn eldningsolja nr 1
10                   tjocka eldningsoljor nr 2-5
11                                      naturgas
12                                      stadsgas
13                                   koksugnsgas
14                        masugnsgas inkl LD-gas
15                                    fj�rrv�rme
16                             k�rnbr�nsleenergi
17                                   vattenkraft
18                                     vindkraft
19                                      elenergi
20                      obearbetade tr�dbr�nslen
21                       bearbetade tr�dbr�nslen
22                                          torv
23                                         sopor
24                                       avlutar
25                             tall och beckolja
26                                        r�olja
27                                  halvfabrikat
28                                 petroleumkoks
29                                        asfalt
30                                     sm�rjolja
31                                       v�golja
32                                     gasbensin
33                                    l�ttbensin
34                                    flygbensin
35                               andra l�ttoljor
36                                petroleumnafta
37                                   flygfotogen
38                 annan fotogen och mellanoljor
Name: energibarare, dtype: object
energifloden
 0                                    1 bruttotillf�rsel
1        1.1 inhemsk tillf�rsel av prim�ra energib�rare
2                                            1.2 import
3                                            1.3 export
4           1.4 lagerf�r�ndringar, statistisk differens
                            ...
63                 9.1.5 anv�ndning inom �vrig industri
64    9.1.1.07 anv�ndning inom massa-, pappers- och ...
65    9.1.2.07 anv�ndning inom kemisk industri, petr...
66    9.1.3.07 anv�ndning inom st�l- och metallverk ...
67    9.1.4.07 anv�ndning inom metallvaru-, maskin-,...
Name: energifloden, Length: 68, dtype: object
<bound method NDFrame.describe of      energibarare                                       energifloden 1984K1  \
0         stenkol                                 1 bruttotillf�rsel  29201
1         stenkol     1.1 inhemsk tillf�rsel av prim�ra energib�rare     ..
2         stenkol                                         1.2 import  19894
3         stenkol                                         1.3 export    435
4         stenkol        1.4 lagerf�r�ndringar, statistisk differens  -9742
...           ...                                                ...    ...
6615     elenergi  9.1.3.07 anv�ndning inom st�l- och metallverk ...    NaN
6616     elenergi  9.1.4.07 anv�ndning inom metallvaru-, maskin-,...    NaN
6617     elenergi               9.1.5 anv�ndning inom �vrig industri    NaN
6618     elenergi                     9.2 anv�ndning inom samf�rdsel    NaN
6619     elenergi  9.3 anv�ndning inom �vrigt (bost�der, service ...    NaN

     1984K2 1984K3 1984K4  1985K1 1985K2 1985K3 1985K4  ... 2015K3 2015K4  \
0     21988  18098  28465   35868  25907  18315  32467  ...  15115  18800
1       136     82    136      ..    163     34    109  ...     ..     ..
2     22533  30698  34617   15866  33174  33391  50156  ...  24336  16254
3        54      0    136     109    109    272   2558  ...      1      0
4       627  12682   6152  -20111   7321  14858  15240  ...   9220  -2546
...     ...    ...    ...     ...    ...    ...    ...  ...    ...    ...
6615    NaN    NaN    NaN     NaN    NaN    NaN    NaN  ...   5972   6721
6616    NaN    NaN    NaN     NaN    NaN    NaN    NaN  ...   4248   4792
6617    NaN    NaN    NaN     NaN    NaN    NaN    NaN  ...   9324  10386
6618    NaN    NaN    NaN     NaN    NaN    NaN    NaN  ...   2430   2992
6619    NaN    NaN    NaN     NaN    NaN    NaN    NaN  ...  48689  72684

     2016K1 2016K2 2016K3 2016K4  2017K1 2017K2 2017K3 2017K4
0     18865  17081  17333  17229   19108  16627  15721  18097
1        ..     ..     ..     ..      ..     ..     ..     ..
2     12378  15833  26697  27785    8930  16907  23460  23335
3         0      0      0      0       0      0      0     12
4     -6487  -1248   9364  10556  -10178    279   7739   5227
...     ...    ...    ...    ...     ...    ...    ...    ...
6615   7157   6926   6214   7067    7132   7150   6552   7398
6616   5263   5054   4291   5184    5220   5051   4471   5342
6617  10494  10264   9367  10462   11020   9965   9331  10620
6618   3305   2678   2470   2902    2970   2423   2250   2804
6619  87262  54326  48494  77597   83949  56851  49056  76229

[6620 rows x 138 columns]>
energibarare    object
energifloden    object
1984K1          object
1984K2          object
1984K3          object
                 ...
2016K4          object
2017K1          object
2017K2          object
2017K3          object
2017K4          object
Length: 138, dtype: object

In [37]:
# Energidata (MWh) efter region, kategori, energityp och år
# region & energy type & year
df33 = pd.read_table('../data/grouped-data/energidata-per-ar.csv', sep=',')

print(df33.columns)

print('region\n', df33.region.drop_duplicates(keep='first').reset_index(drop=True))
print('kategori\n', df33.kategori.drop_duplicates(keep='first').reset_index(drop=True))
print('energityp\n', df33.energityp.drop_duplicates(keep='first').reset_index(drop=True))

print(df33.describe)

print(df33.dtypes)

Index(['region', 'kategori', 'energityp', '1995', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '1990'],
      dtype='object')
region
 0                  00 Riket
1         01 Stockholms l�n
2            03 Uppsala l�n
3      04 S�dermanlands l�n
4      05 �sterg�tlands l�n
               ...
310              2580 Lule�
311              2581 Pite�
312              2582 Boden
313          2583 Haparanda
314             2584 Kiruna
Name: region, Length: 315, dtype: object
kategori
 0                                   2 bruttotillf�rsel
1                       3 insatt f�r omvandling totalt
2                      3.1 insats Vattenkraftstationer
3                             3.2 insats Vindkraftverk
4                             3.3 insats K�rnkraftverk
5                 3.4 insats V�rmekraftverk (ej k�rn-)
6                      3.5 insats Indust.mottrycksanl.
7         3.6.1 insats Kraftv�rmeverk, fj�rrv�rmeprod.
8       3.6.1.1 insats Spec. Fj�rrv�rme m. v�rmepumpar
9                 3.6.2 insats Kraftv�rmeverk, elprod.
10                     3.7 insats Frist�ende v�rmeverk
11    3.7.1 insats Spec.Frist�ende v�rmev. v�rmepumpar
12                                  4 omvandlat totalt
13                  4.1 omvandlat Vattenkraftstationer
14                         4.2 omvandlat Vindkraftverk
15                         4.3 omvandlat K�rnkraftverk
16             4.4 omvandlat V�rmekraftverk (ej k�rn-)
17                 4.5 omvandlat Industr.mottrycksanl.
18                        4.6 omvandlat Kraftv�rmeverk
19             4.6.1omvandlat Spec. Kraftv.v�rmepumpar
20             4.6.2 omvandlat Spec. Kraftv.spillv�rme
21                  4.7 omvandlat Frist�ende v�rmeverk
22      4.7.1 omvandlat Spec.Frist.v�rmev. v�rmepumpar
23       4.7.2 omvandlat Spec.Frist.v�rmev. spillv�rme
24                         5 anv i energisektor totalt
25                5.1 AnvEnSektor Vattenkraftstationer
26                       5.2 AnvEnSektor Vindkraftverk
27                       5.3 AnvEnSektor K�rnkraftverk
28           5.4 AnvEnSektor V�rmekraftverk (ej k�rn-)
29         5.5 AnvEnSektor Industr.mottrycksanl�ggning
30                      5.6 AnvEnSektor Kraftv�rmeverk
31           5.6.1 AnvEnSektor Spec.Kraftv.v�rmepumpar
32                5.7 AnvEnSektor Frist�ende v�rmeverk
33          5.7.1 AnvEnSektor Frist.v�rmev.v�rmepumpar
34                              7 �verf�ringsf�rluster
35                         9 slutlig anv�ndning totalt
36               9.1 slutanv. Jordbruk,skogsbruk,fiske
37                   9.2 slutanv. Industri, byggverks.
38                   9.3 slutanv. Offentlig verksamhet
39                            9.4 slutanv. Transporter
40                        9.5 slutanv. �vriga tj�nster
41                                9.6 slutanv. Hush�ll
42                  9.6.1 slutanv. Spec Hush�ll sm�hus
43         9.6.1.1 slutanv. Spec Hush�ll eluppv.sm�hus
44          9.6.2 slutanv. Spec Hush�ll flerbostadshus
45              9.6.3 slutanv. Spec Hush�ll fritidshus
Name: kategori, dtype: object
energityp
 0            stenkol
1               koks
2             bensin
3             diesel
4     eldningsolja 1
5     eldningsolja>1
6              gasol
7           naturgas
8               torv
9         tr�br�nsle
10           avlutar
11            avfall
12            �vrigt
13        fj�rrv�rme
14                el
15      total energi
Name: energityp, dtype: object
<bound method NDFrame.describe of              region                                     kategori  \
0          00 Riket                           2 bruttotillf�rsel
1          00 Riket               3 insatt f�r omvandling totalt
2          00 Riket              3.1 insats Vattenkraftstationer
3          00 Riket                     3.2 insats Vindkraftverk
4          00 Riket                     3.3 insats K�rnkraftverk
...             ...                                          ...
449185  2584 Kiruna                         9.6 slutanv. Hush�ll
449186  2584 Kiruna           9.6.1 slutanv. Spec Hush�ll sm�hus
449187  2584 Kiruna  9.6.1.1 slutanv. Spec Hush�ll eluppv.sm�hus
449188  2584 Kiruna   9.6.2 slutanv. Spec Hush�ll flerbostadshus
449189  2584 Kiruna       9.6.3 slutanv. Spec Hush�ll fritidshus

           energityp      1995      2000     2001      2002      2003  \
0            stenkol  11654683  10578536  8043433  10572642  12004844
1            stenkol   6297669   3413084  3646483   3529368   5296745
2            stenkol         0         0        0         0         0
3            stenkol         0         0        0         0         0
4            stenkol         0         0        0         0         0
...              ...       ...       ...      ...       ...       ...
449185  total energi       NaN       NaN      NaN       NaN       NaN
449186  total energi       NaN       NaN      NaN       NaN       NaN
449187  total energi       NaN       NaN      NaN       NaN       NaN
449188  total energi       NaN       NaN      NaN       NaN       NaN
449189  total energi       NaN       NaN      NaN       NaN       NaN

            2004      2005      2006      2007     2008    1990
0       19557619  10483148  11553003  10440020  9787924     NaN
1        4494436   3214007        ..   3019659  2457341     NaN
2              0         0         0         0        0     NaN
3              0         0         0         0        0     NaN
4              0         0         0         0        0     NaN
...          ...       ...       ...       ...      ...     ...
449185       NaN       NaN       NaN       NaN      NaN  343738
449186       NaN       NaN       NaN       NaN      NaN  190212
449187       NaN       NaN       NaN       NaN      NaN   21998
449188       NaN       NaN       NaN       NaN      NaN  145089
449189       NaN       NaN       NaN       NaN      NaN    8437

[449190 rows x 14 columns]>
region       object
kategori     object
energityp    object
1995         object
2000         object
2001         object
2002         object
2003         object
2004         object
2005         object
2006         object
2007         object
2008         object
1990         object
dtype: object

In [38]:
# Fjärrvärmeproduktion och bränsleanvändning (MWh) efter region, produktionssätt, bränsletyp och är
# region & energy type & year
df34 = pd.read_table(
    '../data/grouped-data/fjarrvarmeproduktion-per-ar.csv', sep=',', low_memory=False)

print(df34.columns)

df34.rename(columns={'produktionss�tt': 'produktionssatt', 'br�nsletyp': 'bransletyp'}, inplace=True)

print('produktionssatt\n', df34.produktionssatt.drop_duplicates(keep='first').reset_index(drop=True))
print('bransletyp\n', df34.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))

print(df34.describe)

print(df34.dtypes)

Index(['region', 'produktionss�tt', 'br�nsletyp', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='object')
produktionssatt
 0          kraftv�rmeverk
1    frist�ende v�rmeverk
2            elpannor (1)
3         v�rmepumpar (2)
4              spillv�rme
5           r�kgaskondens
6        summa br�nsletyp
Name: produktionssatt, dtype: object
bransletyp
 0         fj�rrv�rmeproduktion
1    flytande (icke f�rnybara)
2        fast (icke f�rnybara)
3         gas (icke f�rnybara)
4         flytande (f�rnybara)
5             fast (f�rnybara)
6              gas (f�rnybara)
7        summa produktionss�tt
Name: bransletyp, dtype: object
<bound method NDFrame.describe of             region   produktionssatt                 bransletyp      2009  \
0         00 Riket    kraftv�rmeverk       fj�rrv�rmeproduktion  28956094
1         00 Riket    kraftv�rmeverk  flytande (icke f�rnybara)   1345208
2         00 Riket    kraftv�rmeverk      fast (icke f�rnybara)   7425543
3         00 Riket    kraftv�rmeverk       gas (icke f�rnybara)        ..
4         00 Riket    kraftv�rmeverk       flytande (f�rnybara)        ..
...            ...               ...                        ...       ...
69883  2584 Kiruna  summa br�nsletyp       gas (icke f�rnybara)         0
69884  2584 Kiruna  summa br�nsletyp       flytande (f�rnybara)         0
69885  2584 Kiruna  summa br�nsletyp           fast (f�rnybara)    145590
69886  2584 Kiruna  summa br�nsletyp            gas (f�rnybara)         0
69887  2584 Kiruna  summa br�nsletyp      summa produktionss�tt    240957

           2010     2011     2012      2013 2014 2015 2016 2017 2018 2019 2020
0      33352707       ..       ..  31812378  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1            ..       ..  1236338        ..  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2            ..       ..  9335117        ..  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3       6505240  3371941  2985013   2878699  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4            ..       ..       ..        ..  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...         ...      ...      ...       ...  ...  ...  ...  ...  ...  ...  ...
69883         0        0        0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
69884         0        0        0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
69885    141631   123981   133891       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
69886         0        0        0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
69887    257475   232903   243795       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[69888 rows x 15 columns]>
region             object
produktionssatt    object
bransletyp         object
2009               object
2010               object
2011               object
2012               object
2013               object
2014               object
2015               object
2016               object
2017               object
2018               object
2019               object
2020               object
dtype: object

In [39]:
# Elproduktion och bränsleanvändning (MWh) efter region, produktionssätt, bränsletyp och är
# region & energy type & year
df35 = pd.read_table(
    '../data/grouped-data/elproduktion-&-bransleanvandning-per-ar.csv', sep=',')

print(df35.columns)

df35.rename(columns={'produktionss�tt': 'produktionssatt', 'br�nsletyp': 'bransletyp'}, inplace=True)

print('produktionssatt\n', df35.produktionssatt.drop_duplicates(keep='first').reset_index(drop=True))
print('bransletyp\n', df35.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))

print(df35.describe)

print(df35.dtypes)

Index(['region', 'produktionss�tt', 'br�nsletyp', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='object')
produktionssatt
 0               kraftv�rmeverk + industriellt mottryck
1    �vrig v�rmekraft (k�rnkraft, kondenskraft o.dyl.)
2                                          vattenkraft
3                                            vindkraft
4                                     summa br�nsletyp
Name: produktionssatt, dtype: object
bransletyp
 0                 elproduktion
1    flytande (icke f�rnybara)
2        fast (icke f�rnybara)
3         gas (icke f�rnybara)
4         flytande (f�rnybara)
5             fast (f�rnybara)
6              gas (f�rnybara)
7        summa produktionss�tt
Name: bransletyp, dtype: object
<bound method NDFrame.describe of             region                         produktionssatt  \
0         00 Riket  kraftv�rmeverk + industriellt mottryck
1         00 Riket  kraftv�rmeverk + industriellt mottryck
2         00 Riket  kraftv�rmeverk + industriellt mottryck
3         00 Riket  kraftv�rmeverk + industriellt mottryck
4         00 Riket  kraftv�rmeverk + industriellt mottryck
...            ...                                     ...
12475  2584 Kiruna                        summa br�nsletyp
12476  2584 Kiruna                        summa br�nsletyp
12477  2584 Kiruna                        summa br�nsletyp
12478  2584 Kiruna                        summa br�nsletyp
12479  2584 Kiruna                        summa br�nsletyp

                      bransletyp      2009      2010      2011      2012  \
0                   elproduktion  15822643  18905397  16881147  15551721
1      flytande (icke f�rnybara)   1070912        ..    915671        ..
2          fast (icke f�rnybara)   2986870        ..        ..   2485721
3           gas (icke f�rnybara)   3803633   5645114   5132547   3388277
4           flytande (f�rnybara)   4915124   5102581   4557074        ..
...                          ...       ...       ...       ...       ...
12475       gas (icke f�rnybara)         0         0         0         0
12476       flytande (f�rnybara)         0         0         0         0
12477           fast (f�rnybara)     16425     21471     19954     17495
12478            gas (f�rnybara)         0         0         0         0
12479      summa produktionss�tt     30883     41742     40113     35200

           2013      2014      2015      2016      2017      2018      2019  \
0      14922809  13302426  13577469  14674133  15070623  15087409  15887123
1        514038        ..    273135    403833        ..    348906    341632
2            ..   2149452   2186608   2072550   2228663   2387084   2104046
3       3188282   2386115   2655982   2852719   2238643   2293599   1838468
4            ..   4840044   4986413   5402304   6653506   6933244   8409747
...         ...       ...       ...       ...       ...       ...       ...
12475         0         0         0         0         0         0         0
12476         0         0         0         0         0         0         0
12477     14706     15291        ..     12725     12776     11393     11353
12478         0         0         0         0         0         0         0
12479     28958     29620        ..     24489     23229     21492     21575

           2020
0      13187095
1        217387
2       1663776
3       1591834
4       8390769
...         ...
12475         0
12476         0
12477     13075
12478         0
12479     24106

[12480 rows x 15 columns]>
region             object
produktionssatt    object
bransletyp         object
2009               object
2010               object
2011               object
2012               object
2013               object
2014               object
2015               object
2016               object
2017               object
2018               object
2019               object
2020               object
dtype: object

In [40]:
# Slutanvändning (MWh) efter region, färbrukarkategori, bränsletyp och är
# fuel type & region & year
df36 = pd.read_table(
    '../data/grouped-data/slutanvandning-per-ar.csv', sep=',', low_memory=False)

print(df36.columns)

df36.rename(columns={'f�rbrukarkategori': 'forbrukarkategori', 'br�nsletyp': 'bransletyp'}, inplace=True)

print('forbrukarkategori\n', df36.forbrukarkategori.drop_duplicates(keep='first').reset_index(drop=True))
print('bransletyp\n', df36.bransletyp.drop_duplicates(keep='first').reset_index(drop=True))

print(df36.describe)

print(df36.dtypes)

Index(['region', 'f�rbrukarkategori', 'br�nsletyp', '2016', '2017', '2018',
       '2019', '2020', '2011', '2012', '2013', '2014', '2015', 'kategori',
       'energityp', '1990'],
      dtype='object')
forbrukarkategori
 0    slutanv. jordbruk,skogsbruk,fiske
1        slutanv. industri, byggverks.
2        slutanv. offentlig verksamhet
3                 slutanv. transporter
4             slutanv. �vriga tj�nster
5                      slutanv. sm�hus
6              slutanv. flerbostadshus
7                  slutanv. fritidshus
8                     summa br�nsletyp
9                                  NaN
Name: forbrukarkategori, dtype: object
bransletyp
 0    flytande (icke f�rnybara)
1        fast (icke f�rnybara)
2         gas (icke f�rnybara)
3         flytande (f�rnybara)
4             fast (f�rnybara)
5              gas (f�rnybara)
6                   fj�rrv�rme
7                           el
8      summa f�rbrukarkategori
9                          NaN
Name: bransletyp, dtype: object
<bound method NDFrame.describe of             region                  forbrukarkategori  \
0         00 Riket  slutanv. jordbruk,skogsbruk,fiske
1         00 Riket  slutanv. jordbruk,skogsbruk,fiske
2         00 Riket  slutanv. jordbruk,skogsbruk,fiske
3         00 Riket  slutanv. jordbruk,skogsbruk,fiske
4         00 Riket  slutanv. jordbruk,skogsbruk,fiske
...            ...                                ...
65029  2584 Kiruna                                NaN
65030  2584 Kiruna                                NaN
65031  2584 Kiruna                                NaN
65032  2584 Kiruna                                NaN
65033  2584 Kiruna                                NaN

                      bransletyp     2016     2017     2018     2019     2020  \
0      flytande (icke f�rnybara)  2329078  2316827  2285608  2672367  2222533
1          fast (icke f�rnybara)        0        0        0        0        0
2           gas (icke f�rnybara)        0        0        0        0        0
3           flytande (f�rnybara)   538665   502765   411461   585739   497105
4               fast (f�rnybara)        0        0        0        0        0
...                          ...      ...      ...      ...      ...      ...
65029                        NaN      NaN      NaN      NaN      NaN      NaN
65030                        NaN      NaN      NaN      NaN      NaN      NaN
65031                        NaN      NaN      NaN      NaN      NaN      NaN
65032                        NaN      NaN      NaN      NaN      NaN      NaN
65033                        NaN      NaN      NaN      NaN      NaN      NaN

      2011 2012 2013 2014 2015                                     kategori  \
0      NaN  NaN  NaN  NaN  NaN                                          NaN
1      NaN  NaN  NaN  NaN  NaN                                          NaN
2      NaN  NaN  NaN  NaN  NaN                                          NaN
3      NaN  NaN  NaN  NaN  NaN                                          NaN
4      NaN  NaN  NaN  NaN  NaN                                          NaN
...    ...  ...  ...  ...  ...                                          ...
65029  NaN  NaN  NaN  NaN  NaN                         9.6 slutanv. Hush�ll
65030  NaN  NaN  NaN  NaN  NaN           9.6.1 slutanv. Spec Hush�ll sm�hus
65031  NaN  NaN  NaN  NaN  NaN  9.6.1.1 slutanv. Spec Hush�ll eluppv.sm�hus
65032  NaN  NaN  NaN  NaN  NaN   9.6.2 slutanv. Spec Hush�ll flerbostadshus
65033  NaN  NaN  NaN  NaN  NaN       9.6.3 slutanv. Spec Hush�ll fritidshus

            energityp   1990
0                 NaN    NaN
1                 NaN    NaN
2                 NaN    NaN
3                 NaN    NaN
4                 NaN    NaN
...               ...    ...
65029  eldningsolja 1  19747
65030  eldningsolja 1   9263
65031  eldningsolja 1      0
65032  eldningsolja 1  10484
65033  eldningsolja 1      0

[65034 rows x 16 columns]>
region               object
forbrukarkategori    object
bransletyp           object
2016                 object
2017                 object
2018                 object
2019                 object
2020                 object
2011                 object
2012                 object
2013                 object
2014                 object
2015                 object
kategori             object
energityp            object
1990                 object
dtype: object